// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/boyxs/train-go/webook/interaction/grpc"
	"github.com/boyxs/train-go/webook/interaction/repository"
	"github.com/boyxs/train-go/webook/interaction/repository/cache"
	"github.com/boyxs/train-go/webook/interaction/repository/dao"
	"github.com/boyxs/train-go/webook/interaction/service"
)

// Injectors from wire.go:

// InitInteractionServer 组装真 dao/cache/repository/service 的 InteractionServer，
// 由集成测试注册到 bufconn gRPC server，发真实请求打通全链路。
// 基础设施走本包 InitDB/InitRedis/InitLogger（连测试库），与 comment/integration/setup 同构。
func InitInteractionServer() *grpc.InteractionServer {
	db := InitDB()
	interactionDAO := dao.NewGormInteractionDAO(db)
	cmdable := InitRedis()
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	loggerX := InitLogger()
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	interactionServer := grpc.NewInteractionServer(interactionService)
	return interactionServer
}
