// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/article_search.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/article_search.go -package=repomocks -destination=./internal/repository/mocks/article_search_mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "gitee.com/train-cloud/geektime-basic-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockArticleSearchRepository is a mock of ArticleSearchRepository interface.
type MockArticleSearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArticleSearchRepositoryMockRecorder
	isgomock struct{}
}

// MockArticleSearchRepositoryMockRecorder is the mock recorder for MockArticleSearchRepository.
type MockArticleSearchRepositoryMockRecorder struct {
	mock *MockArticleSearchRepository
}

// NewMockArticleSearchRepository creates a new mock instance.
func NewMockArticleSearchRepository(ctrl *gomock.Controller) *MockArticleSearchRepository {
	mock := &MockArticleSearchRepository{ctrl: ctrl}
	mock.recorder = &MockArticleSearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleSearchRepository) EXPECT() *MockArticleSearchRepositoryMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MockArticleSearchRepository) Index(ctx context.Context, article domain.Article, vec []float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, article, vec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockArticleSearchRepositoryMockRecorder) Index(ctx, article, vec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockArticleSearchRepository)(nil).Index), ctx, article, vec)
}

// Remove mocks base method.
func (m *MockArticleSearchRepository) Remove(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockArticleSearchRepositoryMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockArticleSearchRepository)(nil).Remove), ctx, id)
}

// Search mocks base method.
func (m *MockArticleSearchRepository) Search(ctx context.Context, text string, vec []float32, offset, limit int) ([]domain.Article, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, text, vec, offset, limit)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockArticleSearchRepositoryMockRecorder) Search(ctx, text, vec, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockArticleSearchRepository)(nil).Search), ctx, text, vec, offset, limit)
}
