// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/article_reader.go
//
// Generated by this command:
//
//	mockgen -source=./repository/article_reader.go -package=repomocks -destination=./repository/mocks/article_reader_mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/internal/domain"
)

// MockArticleReaderRepository is a mock of ArticleReaderRepository interface.
type MockArticleReaderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArticleReaderRepositoryMockRecorder
	isgomock struct{}
}

// MockArticleReaderRepositoryMockRecorder is the mock recorder for MockArticleReaderRepository.
type MockArticleReaderRepositoryMockRecorder struct {
	mock *MockArticleReaderRepository
}

// NewMockArticleReaderRepository creates a new mock instance.
func NewMockArticleReaderRepository(ctrl *gomock.Controller) *MockArticleReaderRepository {
	mock := &MockArticleReaderRepository{ctrl: ctrl}
	mock.recorder = &MockArticleReaderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleReaderRepository) EXPECT() *MockArticleReaderRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockArticleReaderRepository) Delete(ctx context.Context, id, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArticleReaderRepositoryMockRecorder) Delete(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticleReaderRepository)(nil).Delete), ctx, id, uid)
}

// FindById mocks base method.
func (m *MockArticleReaderRepository) FindById(ctx context.Context, id int64) (domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockArticleReaderRepositoryMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockArticleReaderRepository)(nil).FindById), ctx, id)
}

// FindByIds mocks base method.
func (m *MockArticleReaderRepository) FindByIds(ctx context.Context, ids []int64) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIds indicates an expected call of FindByIds.
func (mr *MockArticleReaderRepositoryMockRecorder) FindByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIds", reflect.TypeOf((*MockArticleReaderRepository)(nil).FindByIds), ctx, ids)
}

// ListIdsByAuthor mocks base method.
func (m *MockArticleReaderRepository) ListIdsByAuthor(ctx context.Context, uid int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIdsByAuthor", ctx, uid)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIdsByAuthor indicates an expected call of ListIdsByAuthor.
func (mr *MockArticleReaderRepositoryMockRecorder) ListIdsByAuthor(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIdsByAuthor", reflect.TypeOf((*MockArticleReaderRepository)(nil).ListIdsByAuthor), ctx, uid)
}

// Page mocks base method.
func (m *MockArticleReaderRepository) Page(ctx context.Context, offset, limit int) ([]domain.Article, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Page", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Page indicates an expected call of Page.
func (mr *MockArticleReaderRepositoryMockRecorder) Page(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Page", reflect.TypeOf((*MockArticleReaderRepository)(nil).Page), ctx, offset, limit)
}

// PageByAuthor mocks base method.
func (m *MockArticleReaderRepository) PageByAuthor(ctx context.Context, uid int64, offset, limit int) ([]domain.Article, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PageByAuthor", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PageByAuthor indicates an expected call of PageByAuthor.
func (mr *MockArticleReaderRepositoryMockRecorder) PageByAuthor(ctx, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PageByAuthor", reflect.TypeOf((*MockArticleReaderRepository)(nil).PageByAuthor), ctx, uid, offset, limit)
}

// Upsert mocks base method.
func (m *MockArticleReaderRepository) Upsert(ctx context.Context, article domain.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockArticleReaderRepositoryMockRecorder) Upsert(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockArticleReaderRepository)(nil).Upsert), ctx, article)
}
