// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/chat_conversation.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/chat_conversation.go -package=repomocks -destination=./internal/repository/mocks/chat_conversation_mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockConversationRepository is a mock of ConversationRepository interface.
type MockConversationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConversationRepositoryMockRecorder
	isgomock struct{}
}

// MockConversationRepositoryMockRecorder is the mock recorder for MockConversationRepository.
type MockConversationRepositoryMockRecorder struct {
	mock *MockConversationRepository
}

// NewMockConversationRepository creates a new mock instance.
func NewMockConversationRepository(ctrl *gomock.Controller) *MockConversationRepository {
	mock := &MockConversationRepository{ctrl: ctrl}
	mock.recorder = &MockConversationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationRepository) EXPECT() *MockConversationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConversationRepository) Create(ctx context.Context, conv domain.Conversation) (domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, conv)
	ret0, _ := ret[0].(domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockConversationRepositoryMockRecorder) Create(ctx, conv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConversationRepository)(nil).Create), ctx, conv)
}

// Delete mocks base method.
func (m *MockConversationRepository) Delete(ctx context.Context, uid, convId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uid, convId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConversationRepositoryMockRecorder) Delete(ctx, uid, convId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConversationRepository)(nil).Delete), ctx, uid, convId)
}

// Find mocks base method.
func (m *MockConversationRepository) Find(ctx context.Context, uid, convId int64) (domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, uid, convId)
	ret0, _ := ret[0].(domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockConversationRepositoryMockRecorder) Find(ctx, uid, convId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockConversationRepository)(nil).Find), ctx, uid, convId)
}

// List mocks base method.
func (m *MockConversationRepository) List(ctx context.Context, uid int64) ([]domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, uid)
	ret0, _ := ret[0].([]domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConversationRepositoryMockRecorder) List(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConversationRepository)(nil).List), ctx, uid)
}

// UpdateTitle mocks base method.
func (m *MockConversationRepository) UpdateTitle(ctx context.Context, uid, convId int64, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTitle", ctx, uid, convId, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTitle indicates an expected call of UpdateTitle.
func (mr *MockConversationRepositoryMockRecorder) UpdateTitle(ctx, uid, convId, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTitle", reflect.TypeOf((*MockConversationRepository)(nil).UpdateTitle), ctx, uid, convId, title)
}
