// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/chat_message.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/chat_message.go -package=repomocks -destination=./internal/repository/mocks/chat_message_mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// DelMsgCache mocks base method.
func (m *MockMessageRepository) DelMsgCache(ctx context.Context, convId int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DelMsgCache", ctx, convId)
}

// DelMsgCache indicates an expected call of DelMsgCache.
func (mr *MockMessageRepositoryMockRecorder) DelMsgCache(ctx, convId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelMsgCache", reflect.TypeOf((*MockMessageRepository)(nil).DelMsgCache), ctx, convId)
}

// Insert mocks base method.
func (m *MockMessageRepository) Insert(ctx context.Context, msg domain.Message) (domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, msg)
	ret0, _ := ret[0].(domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockMessageRepositoryMockRecorder) Insert(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMessageRepository)(nil).Insert), ctx, msg)
}

// ListAll mocks base method.
func (m *MockMessageRepository) ListAll(ctx context.Context, convId int64) ([]domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx, convId)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockMessageRepositoryMockRecorder) ListAll(ctx, convId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockMessageRepository)(nil).ListAll), ctx, convId)
}

// ListBefore mocks base method.
func (m *MockMessageRepository) ListBefore(ctx context.Context, convId, beforeId int64, limit int) ([]domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBefore", ctx, convId, beforeId, limit)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBefore indicates an expected call of ListBefore.
func (mr *MockMessageRepositoryMockRecorder) ListBefore(ctx, convId, beforeId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBefore", reflect.TypeOf((*MockMessageRepository)(nil).ListBefore), ctx, convId, beforeId, limit)
}

// ListRecent mocks base method.
func (m *MockMessageRepository) ListRecent(ctx context.Context, convId int64, limit int) ([]domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecent", ctx, convId, limit)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecent indicates an expected call of ListRecent.
func (mr *MockMessageRepositoryMockRecorder) ListRecent(ctx, convId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecent", reflect.TypeOf((*MockMessageRepository)(nil).ListRecent), ctx, convId, limit)
}

// ListRecentLite mocks base method.
func (m *MockMessageRepository) ListRecentLite(ctx context.Context, convId int64, limit int) ([]domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentLite", ctx, convId, limit)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentLite indicates an expected call of ListRecentLite.
func (mr *MockMessageRepositoryMockRecorder) ListRecentLite(ctx, convId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentLite", reflect.TypeOf((*MockMessageRepository)(nil).ListRecentLite), ctx, convId, limit)
}

// UpdateContent mocks base method.
func (m *MockMessageRepository) UpdateContent(ctx context.Context, convId, id int64, content, toolCalls string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContent", ctx, convId, id, content, toolCalls)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContent indicates an expected call of UpdateContent.
func (mr *MockMessageRepositoryMockRecorder) UpdateContent(ctx, convId, id, content, toolCalls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContent", reflect.TypeOf((*MockMessageRepository)(nil).UpdateContent), ctx, convId, id, content, toolCalls)
}

// UpdateFeedback mocks base method.
func (m *MockMessageRepository) UpdateFeedback(ctx context.Context, convId, msgId int64, feedback int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeedback", ctx, convId, msgId, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFeedback indicates an expected call of UpdateFeedback.
func (mr *MockMessageRepositoryMockRecorder) UpdateFeedback(ctx, convId, msgId, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeedback", reflect.TypeOf((*MockMessageRepository)(nil).UpdateFeedback), ctx, convId, msgId, feedback)
}
