// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/click_event.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/click_event.go -package=repomocks -destination=./internal/repository/mocks/click_event_mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockClickEventRepository is a mock of ClickEventRepository interface.
type MockClickEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickEventRepositoryMockRecorder
	isgomock struct{}
}

// MockClickEventRepositoryMockRecorder is the mock recorder for MockClickEventRepository.
type MockClickEventRepositoryMockRecorder struct {
	mock *MockClickEventRepository
}

// NewMockClickEventRepository creates a new mock instance.
func NewMockClickEventRepository(ctrl *gomock.Controller) *MockClickEventRepository {
	mock := &MockClickEventRepository{ctrl: ctrl}
	mock.recorder = &MockClickEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickEventRepository) EXPECT() *MockClickEventRepositoryMockRecorder {
	return m.recorder
}

// Dashboard mocks base method.
func (m *MockClickEventRepository) Dashboard(ctx context.Context) (domain.ClickEventDashboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dashboard", ctx)
	ret0, _ := ret[0].(domain.ClickEventDashboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dashboard indicates an expected call of Dashboard.
func (mr *MockClickEventRepositoryMockRecorder) Dashboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dashboard", reflect.TypeOf((*MockClickEventRepository)(nil).Dashboard), ctx)
}

// RecordClick mocks base method.
func (m *MockClickEventRepository) RecordClick(ctx context.Context, click domain.ClickEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClick", ctx, click)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClick indicates an expected call of RecordClick.
func (mr *MockClickEventRepositoryMockRecorder) RecordClick(ctx, click any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClick", reflect.TypeOf((*MockClickEventRepository)(nil).RecordClick), ctx, click)
}
