// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/interaction.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/interaction.go -package=repomocks -destination=./internal/repository/mocks/interaction_mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockInteractionRepository is a mock of InteractionRepository interface.
type MockInteractionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionRepositoryMockRecorder
	isgomock struct{}
}

// MockInteractionRepositoryMockRecorder is the mock recorder for MockInteractionRepository.
type MockInteractionRepositoryMockRecorder struct {
	mock *MockInteractionRepository
}

// NewMockInteractionRepository creates a new mock instance.
func NewMockInteractionRepository(ctrl *gomock.Controller) *MockInteractionRepository {
	mock := &MockInteractionRepository{ctrl: ctrl}
	mock.recorder = &MockInteractionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractionRepository) EXPECT() *MockInteractionRepositoryMockRecorder {
	return m.recorder
}

// CancelCollect mocks base method.
func (m *MockInteractionRepository) CancelCollect(ctx context.Context, uid int64, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelCollect", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelCollect indicates an expected call of CancelCollect.
func (mr *MockInteractionRepositoryMockRecorder) CancelCollect(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelCollect", reflect.TypeOf((*MockInteractionRepository)(nil).CancelCollect), ctx, uid, biz, bizId)
}

// CancelLike mocks base method.
func (m *MockInteractionRepository) CancelLike(ctx context.Context, uid int64, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelLike", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelLike indicates an expected call of CancelLike.
func (mr *MockInteractionRepositoryMockRecorder) CancelLike(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelLike", reflect.TypeOf((*MockInteractionRepository)(nil).CancelLike), ctx, uid, biz, bizId)
}

// Collect mocks base method.
func (m *MockInteractionRepository) Collect(ctx context.Context, uid int64, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Collect indicates an expected call of Collect.
func (mr *MockInteractionRepositoryMockRecorder) Collect(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockInteractionRepository)(nil).Collect), ctx, uid, biz, bizId)
}

// FindByBizIds mocks base method.
func (m *MockInteractionRepository) FindByBizIds(ctx context.Context, biz string, bizIds []int64) ([]domain.Interaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBizIds", ctx, biz, bizIds)
	ret0, _ := ret[0].([]domain.Interaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBizIds indicates an expected call of FindByBizIds.
func (mr *MockInteractionRepositoryMockRecorder) FindByBizIds(ctx, biz, bizIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBizIds", reflect.TypeOf((*MockInteractionRepository)(nil).FindByBizIds), ctx, biz, bizIds)
}

// FindInteraction mocks base method.
func (m *MockInteractionRepository) FindInteraction(ctx context.Context, uid int64, biz string, bizId int64) (domain.Interaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInteraction", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(domain.Interaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInteraction indicates an expected call of FindInteraction.
func (mr *MockInteractionRepositoryMockRecorder) FindInteraction(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInteraction", reflect.TypeOf((*MockInteractionRepository)(nil).FindInteraction), ctx, uid, biz, bizId)
}

// FindUserState mocks base method.
func (m *MockInteractionRepository) FindUserState(ctx context.Context, uid int64, biz string, bizId int64) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserState", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindUserState indicates an expected call of FindUserState.
func (mr *MockInteractionRepositoryMockRecorder) FindUserState(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserState", reflect.TypeOf((*MockInteractionRepository)(nil).FindUserState), ctx, uid, biz, bizId)
}

// IncrReadCount mocks base method.
func (m *MockInteractionRepository) IncrReadCount(ctx context.Context, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrReadCount", ctx, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrReadCount indicates an expected call of IncrReadCount.
func (mr *MockInteractionRepositoryMockRecorder) IncrReadCount(ctx, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrReadCount", reflect.TypeOf((*MockInteractionRepository)(nil).IncrReadCount), ctx, biz, bizId)
}

// Like mocks base method.
func (m *MockInteractionRepository) Like(ctx context.Context, uid int64, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockInteractionRepositoryMockRecorder) Like(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockInteractionRepository)(nil).Like), ctx, uid, biz, bizId)
}

// ListCollectedBizIds mocks base method.
func (m *MockInteractionRepository) ListCollectedBizIds(ctx context.Context, uid int64, biz string, limit int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectedBizIds", ctx, uid, biz, limit)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollectedBizIds indicates an expected call of ListCollectedBizIds.
func (mr *MockInteractionRepositoryMockRecorder) ListCollectedBizIds(ctx, uid, biz, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectedBizIds", reflect.TypeOf((*MockInteractionRepository)(nil).ListCollectedBizIds), ctx, uid, biz, limit)
}

// ListHotBizIds mocks base method.
func (m *MockInteractionRepository) ListHotBizIds(ctx context.Context, biz string, limit int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHotBizIds", ctx, biz, limit)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHotBizIds indicates an expected call of ListHotBizIds.
func (mr *MockInteractionRepositoryMockRecorder) ListHotBizIds(ctx, biz, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHotBizIds", reflect.TypeOf((*MockInteractionRepository)(nil).ListHotBizIds), ctx, biz, limit)
}
