// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/ranking.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/ranking.go -package=repomocks -destination=./internal/repository/mocks/ranking_mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockRankingRepository is a mock of RankingRepository interface.
type MockRankingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRankingRepositoryMockRecorder
	isgomock struct{}
}

// MockRankingRepositoryMockRecorder is the mock recorder for MockRankingRepository.
type MockRankingRepositoryMockRecorder struct {
	mock *MockRankingRepository
}

// NewMockRankingRepository creates a new mock instance.
func NewMockRankingRepository(ctrl *gomock.Controller) *MockRankingRepository {
	mock := &MockRankingRepository{ctrl: ctrl}
	mock.recorder = &MockRankingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingRepository) EXPECT() *MockRankingRepositoryMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockRankingRepository) Archive(ctx context.Context, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockRankingRepositoryMockRecorder) Archive(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockRankingRepository)(nil).Archive), ctx, date)
}

// IncrScore mocks base method.
func (m *MockRankingRepository) IncrScore(ctx context.Context, date, dim, cat string, articleId int64, delta float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrScore", ctx, date, dim, cat, articleId, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrScore indicates an expected call of IncrScore.
func (mr *MockRankingRepositoryMockRecorder) IncrScore(ctx, date, dim, cat, articleId, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrScore", reflect.TypeOf((*MockRankingRepository)(nil).IncrScore), ctx, date, dim, cat, articleId, delta)
}

// ListArchiveDates mocks base method.
func (m *MockRankingRepository) ListArchiveDates(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArchiveDates", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArchiveDates indicates an expected call of ListArchiveDates.
func (mr *MockRankingRepositoryMockRecorder) ListArchiveDates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArchiveDates", reflect.TypeOf((*MockRankingRepository)(nil).ListArchiveDates), ctx)
}

// PrevRanks mocks base method.
func (m *MockRankingRepository) PrevRanks(ctx context.Context, date, dim, cat string, articleIds []int64) (map[int64]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrevRanks", ctx, date, dim, cat, articleIds)
	ret0, _ := ret[0].(map[int64]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrevRanks indicates an expected call of PrevRanks.
func (mr *MockRankingRepositoryMockRecorder) PrevRanks(ctx, date, dim, cat, articleIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrevRanks", reflect.TypeOf((*MockRankingRepository)(nil).PrevRanks), ctx, date, dim, cat, articleIds)
}

// ReplaceTop mocks base method.
func (m *MockRankingRepository) ReplaceTop(ctx context.Context, date, dim, cat string, items []domain.ArticleRanking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTop", ctx, date, dim, cat, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTop indicates an expected call of ReplaceTop.
func (mr *MockRankingRepositoryMockRecorder) ReplaceTop(ctx, date, dim, cat, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTop", reflect.TypeOf((*MockRankingRepository)(nil).ReplaceTop), ctx, date, dim, cat, items)
}

// Top mocks base method.
func (m *MockRankingRepository) Top(ctx context.Context, date, dim, cat string, limit int) ([]domain.ArticleRanking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Top", ctx, date, dim, cat, limit)
	ret0, _ := ret[0].([]domain.ArticleRanking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Top indicates an expected call of Top.
func (mr *MockRankingRepositoryMockRecorder) Top(ctx, date, dim, cat, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Top", reflect.TypeOf((*MockRankingRepository)(nil).Top), ctx, date, dim, cat, limit)
}
