// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/boyxs/train-go/webook/relation/grpc"
	"github.com/boyxs/train-go/webook/relation/repository"
	"github.com/boyxs/train-go/webook/relation/repository/cache"
	"github.com/boyxs/train-go/webook/relation/repository/dao"
	"github.com/boyxs/train-go/webook/relation/service"
)

// Injectors from wire.go:

// InitRelationServer 组装真 dao/cache/repository/service 的 RelationServer，供集成测试注册到 bufconn gRPC server，
// 经 RelationServiceClient 发真实请求打通 gRPC → service → repository → dao/cache → MySQL/Redis 全链路。
// 与 interaction/integration/setup 同构（同为 gRPC 服务 + Cache-Aside）。
func InitRelationServer() *grpc.RelationServer {
	db := InitDB()
	relationDAO := dao.NewGormRelationDAO(db)
	cmdable := InitRedis()
	relationCache := cache.NewRedisRelationCache(cmdable)
	loggerX := InitLogger()
	relationRepository := repository.NewCacheRelationRepository(relationDAO, relationCache, loggerX)
	relationService := service.NewInternalRelationService(relationRepository)
	relationServer := grpc.NewRelationServer(relationService)
	return relationServer
}
