// Code generated by MockGen. DO NOT EDIT.
// Source: ./redislock.go
//
// Generated by this command:
//
//	mockgen -source ./redislock.go -package lockmocks -destination ./mocks/lock_mock.go
//

// Package lockmocks is a generated GoMock package.
package lockmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	redislock "github.com/boyxs/train-go/webook/pkg/redislock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Lock mocks base method.
func (m *MockClient) Lock(ctx context.Context, key string, opts ...redislock.Options) (redislock.RedisLock, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Lock", varargs...)
	ret0, _ := ret[0].(redislock.RedisLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock.
func (mr *MockClientMockRecorder) Lock(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockClient)(nil).Lock), varargs...)
}

// TryLock mocks base method.
func (m *MockClient) TryLock(ctx context.Context, key string, opts ...redislock.Options) (redislock.RedisLock, bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TryLock", varargs...)
	ret0, _ := ret[0].(redislock.RedisLock)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryLock indicates an expected call of TryLock.
func (mr *MockClientMockRecorder) TryLock(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryLock", reflect.TypeOf((*MockClient)(nil).TryLock), varargs...)
}

// MockRedisLock is a mock of RedisLock interface.
type MockRedisLock struct {
	ctrl     *gomock.Controller
	recorder *MockRedisLockMockRecorder
	isgomock struct{}
}

// MockRedisLockMockRecorder is the mock recorder for MockRedisLock.
type MockRedisLockMockRecorder struct {
	mock *MockRedisLock
}

// NewMockRedisLock creates a new mock instance.
func NewMockRedisLock(ctrl *gomock.Controller) *MockRedisLock {
	mock := &MockRedisLock{ctrl: ctrl}
	mock.recorder = &MockRedisLockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisLock) EXPECT() *MockRedisLockMockRecorder {
	return m.recorder
}

// Fence mocks base method.
func (m *MockRedisLock) Fence() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fence")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Fence indicates an expected call of Fence.
func (mr *MockRedisLockMockRecorder) Fence() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fence", reflect.TypeOf((*MockRedisLock)(nil).Fence))
}

// ForceUnlock mocks base method.
func (m *MockRedisLock) ForceUnlock(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceUnlock", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceUnlock indicates an expected call of ForceUnlock.
func (mr *MockRedisLockMockRecorder) ForceUnlock(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceUnlock", reflect.TypeOf((*MockRedisLock)(nil).ForceUnlock), ctx)
}

// HoldCount mocks base method.
func (m *MockRedisLock) HoldCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HoldCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HoldCount indicates an expected call of HoldCount.
func (mr *MockRedisLockMockRecorder) HoldCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HoldCount", reflect.TypeOf((*MockRedisLock)(nil).HoldCount), ctx)
}

// IsHeldByMe mocks base method.
func (m *MockRedisLock) IsHeldByMe(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHeldByMe", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsHeldByMe indicates an expected call of IsHeldByMe.
func (mr *MockRedisLockMockRecorder) IsHeldByMe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHeldByMe", reflect.TypeOf((*MockRedisLock)(nil).IsHeldByMe), ctx)
}

// IsLocked mocks base method.
func (m *MockRedisLock) IsLocked(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocked", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLocked indicates an expected call of IsLocked.
func (mr *MockRedisLockMockRecorder) IsLocked(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocked", reflect.TypeOf((*MockRedisLock)(nil).IsLocked), ctx)
}

// Key mocks base method.
func (m *MockRedisLock) Key() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key")
	ret0, _ := ret[0].(string)
	return ret0
}

// Key indicates an expected call of Key.
func (mr *MockRedisLockMockRecorder) Key() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockRedisLock)(nil).Key))
}

// Refresh mocks base method.
func (m *MockRedisLock) Refresh(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockRedisLockMockRecorder) Refresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockRedisLock)(nil).Refresh), ctx)
}

// TTL mocks base method.
func (m *MockRedisLock) TTL(ctx context.Context) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTL", ctx)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TTL indicates an expected call of TTL.
func (mr *MockRedisLockMockRecorder) TTL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTL", reflect.TypeOf((*MockRedisLock)(nil).TTL), ctx)
}

// Token mocks base method.
func (m *MockRedisLock) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockRedisLockMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockRedisLock)(nil).Token))
}

// Unlock mocks base method.
func (m *MockRedisLock) Unlock(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockRedisLockMockRecorder) Unlock(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockRedisLock)(nil).Unlock), ctx)
}
