// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"

	"github.com/boyxs/train-go/webook/internal/events/article"
	"github.com/boyxs/train-go/webook/internal/events/interaction"
	"github.com/boyxs/train-go/webook/internal/events/relation"
	"github.com/boyxs/train-go/webook/internal/grpc"
	"github.com/boyxs/train-go/webook/internal/ioc"
	"github.com/boyxs/train-go/webook/internal/repository"
	"github.com/boyxs/train-go/webook/internal/repository/cache"
	"github.com/boyxs/train-go/webook/internal/repository/dao"
	"github.com/boyxs/train-go/webook/internal/service"
	"github.com/boyxs/train-go/webook/internal/web"
	"github.com/boyxs/train-go/webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitWebServer() (App, func(), error) {
	loggerX := ioc.InitLogger()
	universalClient := ioc.InitRedis()
	tracerProvider, cleanup, err := ioc.InitOTel()
	if err != nil {
		return App{}, nil, err
	}
	v := ioc.InitMiddlewares(loggerX, universalClient, tracerProvider)
	handler := ioc.InitJwtHandler(universalClient)
	timezoneReady := ioc.InitTimezone()
	db := ioc.InitDB(timezoneReady, loggerX)
	userDAO := dao.NewGormUserDAO(db)
	userCache := cache.NewRedisUserCache(universalClient)
	userRepository := repository.NewRedisUserRepository(userDAO, userCache, loggerX)
	client := ioc.InitLockClient(universalClient)
	userService := service.NewInternalUserService(userRepository, client, loggerX)
	codeCache := cache.NewRedisCodeCache(universalClient)
	codeRepository := repository.NewRedisCodeRepository(codeCache)
	smsService := ioc.InitSmsService(universalClient, loggerX)
	codeService := service.NewSmsCodeService(codeRepository, smsService)
	userHandler := web.NewInternalUserHandler(handler, userService, codeService, loggerX)
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	articleCache := cache.NewRedisArticleCache(universalClient, loggerX)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache, loggerX)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderNewDAO := dao.NewGormArticleReaderNewDAO(db)
	switchReader := ioc.InitMigratorSDKSwitchReader(universalClient, loggerX)
	dualWriter := ioc.InitMigratorSDKDualWriter(universalClient, loggerX)
	taskName := ioc.InitMigratorSDKTaskName()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleReaderNewDAO, articleCache, switchReader, dualWriter, taskName, loggerX)
	clientv3Client, cleanup2, err := ioc.InitEtcdClient()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	prometheusBuilder := ioc.InitGRPCMetrics()
	searchConn, cleanup3, err := ioc.InitSearchConn(clientv3Client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	searchServiceClient := ioc.InitSearchClient(searchConn)
	tagConn, cleanup4, err := ioc.InitTagConn(clientv3Client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	tagServiceClient := ioc.InitTagClient(tagConn)
	interactionConn, cleanup5, err := ioc.InitInteractionConn(clientv3Client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	interactionServiceClient := ioc.InitInteractionClient(interactionConn)
	rankingCache := cache.NewRedisArticleRankingCache(universalClient, loggerX)
	rankingDAO := dao.NewGormArticleRankingDAO(db)
	rankingRepository := repository.NewCacheArticleRankingRepository(rankingCache, rankingDAO, loggerX)
	pool, cleanup6 := ioc.InitRankingBoostPool(loggerX)
	kafkaConfig := ioc.InitKafkaConfig()
	config := ioc.InitSaramaConfig(kafkaConfig)
	producer := ioc.InitEventProducer(kafkaConfig, config, loggerX)
	interactionEventProducer := interaction.NewSaramaInteractionEventProducer(producer)
	interactionService := ioc.InitInteractionService(interactionServiceClient, rankingRepository, pool, interactionEventProducer, loggerX)
	articleSearchService := service.NewGRPCArticleSearchService(searchServiceClient, tagServiceClient, interactionService, loggerX)
	commentConn, cleanup7, err := ioc.InitCommentConn(clientv3Client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	commentServiceClient := ioc.InitCommentClient(commentConn)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository, interactionService, commentServiceClient, loggerX)
	tagService := service.NewGRPCTagService(tagServiceClient, searchServiceClient, articleReaderService, interactionService, loggerX)
	articleEventProducer := article.NewSaramaArticleEventProducer(producer)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository, articleSearchService, tagService, articleEventProducer, loggerX)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, tagService, loggerX)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	oAuth2Service := ioc.InitWechatOAuth2Service()
	oAuth2Handler := web.NewOAuth2WechatHandler(handler, oAuth2Service, userService)
	articleSearchHandler := web.NewInternalArticleSearchHandler(articleSearchService, loggerX)
	tagHandler := web.NewInternalTagHandler(tagService, loggerX)
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	clickEventCache := cache.NewRedisAIClickEventCache(universalClient)
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	clickEventHandler := web.NewAIClickEventHandler(clickEventService, loggerX)
	llmConfig := ioc.InitLLMConfig()
	llmClient := ioc.InitLLMClient(llmConfig, loggerX)
	articlePolishService := service.NewAIArticlePolishService(llmClient)
	articlePolishHandler := web.NewAIArticlePolishHandler(articlePolishService, universalClient, loggerX)
	rankingService := service.NewArticleRankingService(rankingRepository, articleReaderRepository, interactionService, clickEventService, loggerX)
	rankingHandler := web.NewArticleRankingHandler(rankingService, loggerX)
	commentService := service.NewGRPCCommentService(commentServiceClient, interactionService, userService, loggerX)
	commentHandler := web.NewInternalCommentHandler(commentService)
	relationConn, cleanup8, err := ioc.InitRelationConn(clientv3Client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	relationServiceClient := ioc.InitRelationClient(relationConn)
	relationEventProducer := relation.NewSaramaRelationEventProducer(producer)
	relationService := service.NewGRPCRelationService(relationServiceClient, userService, relationEventProducer, loggerX)
	relationHandler := web.NewInternalRelationHandler(relationService)
	feedConn, cleanup9, err := ioc.InitFeedConn(clientv3Client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	feedServiceClient := ioc.InitFeedClient(feedConn)
	feedService := service.NewGRPCFeedService(feedServiceClient, articleReaderService, interactionService, commentServiceClient, tagService, userService, loggerX)
	feedHandler := web.NewInternalFeedHandler(feedService)
	engine := ioc.InitWebServer(v, userHandler, articleAuthorHandler, articleReaderHandler, interactionHandler, oAuth2Handler, articleSearchHandler, tagHandler, clickEventHandler, articlePolishHandler, rankingHandler, commentHandler, relationHandler, feedHandler)
	articleReaderServer := grpc.NewArticleReaderServer(articleReaderService)
	rankingJobServer := grpc.NewRankingJobServer(rankingService)
	server := ioc.InitGRPCServer(articleReaderServer, rankingJobServer, clientv3Client, prometheusBuilder, loggerX)
	app := App{
		Server:     engine,
		GRPCServer: server,
	}
	return app, func() {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// tagSearchProviderSet tag/search 下游 gRPC client + core BFF 服务（持 client + 聚合，同构 GRPCCommentService）。
// search 已从 core 抽出为独立服务，core 退为 client（不再持 ES/embedding）。
var tagSearchProviderSet = wire.NewSet(ioc.InitSearchConn, ioc.InitSearchClient, ioc.InitTagConn, ioc.InitTagClient, service.NewGRPCArticleSearchService, service.NewGRPCTagService)

// clickEventProviderSet 点击埋点模块
var clickEventProviderSet = wire.NewSet(dao.NewGormAIClickEventDAO, cache.NewRedisAIClickEventCache, repository.NewCacheAIClickEventRepository, service.NewAIClickEventService)

// polishProviderSet 文章润色模块（含 LLM 配置/客户端 — 之前在 chatProviderSet 里）
var polishProviderSet = wire.NewSet(ioc.InitLLMConfig, ioc.InitLLMClient, service.NewAIArticlePolishService)

// articleRankingProviderSet 文章榜单模块（数据 + 重算逻辑留 core；定时调度由 webook-worker 经 RankingJobService gRPC 触发）
var articleRankingProviderSet = wire.NewSet(dao.NewGormArticleRankingDAO, cache.NewRedisArticleRankingCache, repository.NewCacheArticleRankingRepository, service.NewArticleRankingService, web.NewArticleRankingHandler, grpc.NewRankingJobServer)

// migratorSDKProviderSet 业务侧迁移 SDK（默认 NoOp 零开销，yaml migrator.sdk.enabled=true 切 Redis 实现）
var migratorSDKProviderSet = wire.NewSet(ioc.InitMigratorSDKSwitchReader, ioc.InitMigratorSDKDualWriter, ioc.InitMigratorSDKTaskName, dao.NewGormArticleReaderNewDAO)

// kafkaProviderSet Kafka 生产侧：core 只产 read 事件，消费由 webook-worker（调度器）负责。
var kafkaProviderSet = wire.NewSet(ioc.InitKafkaConfig, ioc.InitSaramaConfig, ioc.InitEventProducer, interaction.NewSaramaInteractionEventProducer, relation.NewSaramaRelationEventProducer, article.NewSaramaArticleEventProducer)

// App 应用入口：Web 服务 + gRPC 服务（消费者/定时任务已抽到 webook-worker）。
type App struct {
	Server     *gin.Engine
	GRPCServer *grpcx.Server
}
