// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/robfig/cron/v3"

	"github.com/webook/internal/events"
	"github.com/webook/internal/events/interaction"
	"github.com/webook/internal/grpc"
	"github.com/webook/internal/ioc"
	"github.com/webook/internal/job"
	"github.com/webook/internal/repository"
	"github.com/webook/internal/repository/cache"
	"github.com/webook/internal/repository/dao"
	"github.com/webook/internal/service"
	"github.com/webook/internal/web"
	"github.com/webook/pkg/grpcx"

	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer() (App, func(), error) {
	loggerX := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	tracerProvider, cleanup, err := ioc.InitOTel()
	if err != nil {
		return App{}, nil, err
	}
	v := ioc.InitMiddlewares(loggerX, cmdable, tracerProvider)
	handler := ioc.InitJwtHandler(cmdable)
	timezoneReady := ioc.InitTimezone()
	db := ioc.InitDB(timezoneReady, loggerX)
	userDAO := dao.NewGormUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewRedisUserRepository(userDAO, userCache)
	userService := service.NewInternalUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewRedisCodeRepository(codeCache)
	smsService := ioc.InitSmsService(cmdable, loggerX)
	codeService := service.NewSmsCodeService(codeRepository, smsService)
	userHandler := web.NewInternalUserHandler(handler, userService, codeService, loggerX)
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable, loggerX)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderNewDAO := dao.NewGormArticleReaderNewDAO(db)
	switchReader := ioc.InitMigratorSDKSwitchReader(cmdable, loggerX)
	dualWriter := ioc.InitMigratorSDKDualWriter(cmdable, loggerX)
	taskName := ioc.InitMigratorSDKTaskName()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleReaderNewDAO, articleCache, switchReader, dualWriter, taskName, loggerX)
	typedClient := ioc.InitESClient()
	articleSearchDAO := dao.NewElasticArticleDAO(typedClient)
	articleSearchRepository := repository.NewESArticleSearchRepository(articleSearchDAO)
	ollamaConfig := ioc.InitOllamaEmbeddingConfig()
	config := ioc.InitEmbeddingConfig()
	client := ioc.InitEmbeddingClient(ollamaConfig, config, cmdable, loggerX)
	articleSearchService := service.NewArticleSearchService(articleSearchRepository, client, loggerX)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository, articleSearchService, loggerX)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	rankingCache := cache.NewRedisArticleRankingCache(cmdable, loggerX)
	rankingDAO := dao.NewGormArticleRankingDAO(db)
	rankingRepository := repository.NewCacheArticleRankingRepository(rankingCache, rankingDAO, loggerX)
	kafkaConfig := ioc.InitKafkaConfig()
	saramaConfig := ioc.InitSaramaConfig(kafkaConfig)
	syncProducer := ioc.InitSaramaSyncProducer(kafkaConfig, saramaConfig)
	producer := ioc.InitEventProducer(syncProducer, loggerX)
	interactionEventProducer := interaction.NewSaramaInteractionEventProducer(producer)
	interactionService := ioc.InitInteractionService(interactionRepository, rankingRepository, interactionEventProducer, loggerX)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, loggerX)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	oAuth2Service := ioc.InitWechatOAuth2Service()
	oAuth2Handler := web.NewOAuth2WechatHandler(handler, oAuth2Service, userService)
	articleSearchHandler := web.NewInternalArticleSearchHandler(articleSearchService, loggerX)
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	clickEventCache := cache.NewRedisAIClickEventCache(cmdable)
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	clickEventHandler := web.NewAIClickEventHandler(clickEventService, loggerX)
	llmConfig := ioc.InitLLMConfig()
	llmClient := ioc.InitLLMClient(llmConfig, loggerX)
	articlePolishService := service.NewAIArticlePolishService(llmClient)
	articlePolishHandler := web.NewAIArticlePolishHandler(articlePolishService, cmdable, loggerX)
	rankingService := service.NewArticleRankingService(rankingRepository, articleReaderRepository, interactionRepository, clickEventService, loggerX)
	rankingHandler := web.NewArticleRankingHandler(rankingService, loggerX)
	engine := ioc.InitWebServer(v, userHandler, articleAuthorHandler, articleReaderHandler, interactionHandler, oAuth2Handler, articleSearchHandler, clickEventHandler, articlePolishHandler, rankingHandler)
	searchServer := grpc.NewSearchServer(articleSearchService)
	articleReaderServer := grpc.NewArticleReaderServer(articleReaderService)
	interactionServer := grpc.NewInteractionServer(interactionService)
	clientv3Client, cleanup2, err := ioc.InitEtcdClient()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	server := ioc.InitGRPCServer(searchServer, articleReaderServer, interactionServer, clientv3Client, loggerX)
	saramaClient := ioc.InitSaramaClient(kafkaConfig, saramaConfig)
	consumerConfig := ioc.InitInteractionConsumerConfig(kafkaConfig)
	consumer := interaction.NewSaramaInteractionEventConsumer(saramaClient, interactionRepository, consumerConfig, loggerX)
	redislockxClient := ioc.InitLockClient(cmdable)
	metrics := ioc.InitCronMetrics()
	wrapper := ioc.InitCronWrapper(redislockxClient, metrics, loggerX)
	rankingJob := job.NewRankingJob(rankingService, wrapper)
	cron, cleanup3 := ioc.InitCron(rankingJob, loggerX)
	app := App{
		Server:      engine,
		GRPCServer:  server,
		Consumer:    consumer,
		RankingCron: cron,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// searchProviderSet 搜索模块的 Wire Provider 集合（不含 Handler）
var searchProviderSet = wire.NewSet(ioc.InitESClient, ioc.InitOllamaEmbeddingConfig, ioc.InitEmbeddingConfig, ioc.InitEmbeddingClient, dao.NewElasticArticleDAO, repository.NewESArticleSearchRepository, service.NewArticleSearchService)

// clickEventProviderSet 点击埋点模块
var clickEventProviderSet = wire.NewSet(dao.NewGormAIClickEventDAO, cache.NewRedisAIClickEventCache, repository.NewCacheAIClickEventRepository, service.NewAIClickEventService)

// polishProviderSet 文章润色模块（含 LLM 配置/客户端 — 之前在 chatProviderSet 里）
var polishProviderSet = wire.NewSet(ioc.InitLLMConfig, ioc.InitLLMClient, service.NewAIArticlePolishService)

// articleRankingProviderSet 文章榜单模块
var articleRankingProviderSet = wire.NewSet(dao.NewGormArticleRankingDAO, cache.NewRedisArticleRankingCache, repository.NewCacheArticleRankingRepository, service.NewArticleRankingService, job.NewRankingJob, web.NewArticleRankingHandler)

// migratorSDKProviderSet 业务侧迁移 SDK（默认 NoOp 零开销，yaml migrator.sdk.enabled=true 切 Redis 实现）
var migratorSDKProviderSet = wire.NewSet(ioc.InitMigratorSDKSwitchReader, ioc.InitMigratorSDKDualWriter, ioc.InitMigratorSDKTaskName, dao.NewGormArticleReaderNewDAO)

// kafkaProviderSet Kafka 基础设施 + 互动事件
var kafkaProviderSet = wire.NewSet(ioc.InitKafkaConfig, ioc.InitSaramaConfig, ioc.InitSaramaSyncProducer, ioc.InitSaramaClient, ioc.InitEventProducer, ioc.InitInteractionConsumerConfig, interaction.NewSaramaInteractionEventProducer, interaction.NewSaramaInteractionEventConsumer)

// App 应用入口，包含 Web 服务、后台消费者、gRPC 服务。
type App struct {
	Server      *gin.Engine
	GRPCServer  *grpcx.Server
	Consumer    events.Consumer
	RankingCron *cron.Cron
}
