// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"

	"github.com/boyxs/train-go/webook/internal/events/interaction"
	"github.com/boyxs/train-go/webook/internal/events/relation"
	"github.com/boyxs/train-go/webook/internal/grpc"
	"github.com/boyxs/train-go/webook/internal/ioc"
	"github.com/boyxs/train-go/webook/internal/repository"
	"github.com/boyxs/train-go/webook/internal/repository/cache"
	"github.com/boyxs/train-go/webook/internal/repository/dao"
	"github.com/boyxs/train-go/webook/internal/service"
	"github.com/boyxs/train-go/webook/internal/web"
	"github.com/boyxs/train-go/webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitWebServer() (App, func(), error) {
	loggerX := ioc.InitLogger()
	client := ioc.InitRedis()
	tracerProvider, cleanup, err := ioc.InitOTel()
	if err != nil {
		return App{}, nil, err
	}
	v := ioc.InitMiddlewares(loggerX, client, tracerProvider)
	handler := ioc.InitJwtHandler(client)
	timezoneReady := ioc.InitTimezone()
	db := ioc.InitDB(timezoneReady, loggerX)
	userDAO := dao.NewGormUserDAO(db)
	userCache := cache.NewRedisUserCache(client)
	userRepository := repository.NewRedisUserRepository(userDAO, userCache)
	redislockClient := ioc.InitLockClient(client)
	userService := service.NewInternalUserService(userRepository, redislockClient, loggerX)
	codeCache := cache.NewRedisCodeCache(client)
	codeRepository := repository.NewRedisCodeRepository(codeCache)
	smsService := ioc.InitSmsService(client, loggerX)
	codeService := service.NewSmsCodeService(codeRepository, smsService)
	userHandler := web.NewInternalUserHandler(handler, userService, codeService, loggerX)
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	articleCache := cache.NewRedisArticleCache(client, loggerX)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderNewDAO := dao.NewGormArticleReaderNewDAO(db)
	switchReader := ioc.InitMigratorSDKSwitchReader(client, loggerX)
	dualWriter := ioc.InitMigratorSDKDualWriter(client, loggerX)
	taskName := ioc.InitMigratorSDKTaskName()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleReaderNewDAO, articleCache, switchReader, dualWriter, taskName, loggerX)
	typedClient := ioc.InitESClient()
	articleSearchDAO := dao.NewElasticArticleDAO(typedClient)
	articleSearchRepository := repository.NewESArticleSearchRepository(articleSearchDAO)
	ollamaConfig := ioc.InitOllamaEmbeddingConfig()
	config := ioc.InitEmbeddingConfig()
	embeddingClient := ioc.InitEmbeddingClient(ollamaConfig, config, client, loggerX)
	articleSearchService := service.NewArticleSearchService(articleSearchRepository, embeddingClient, loggerX)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository, articleSearchService, loggerX)
	clientv3Client, cleanup2, err := ioc.InitEtcdClient()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	prometheusBuilder := ioc.InitGRPCMetrics()
	interactionConn, cleanup3, err := ioc.InitInteractionConn(clientv3Client, prometheusBuilder)
	if err != nil {
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	interactionServiceClient := ioc.InitInteractionClient(interactionConn)
	rankingCache := cache.NewRedisArticleRankingCache(client, loggerX)
	rankingDAO := dao.NewGormArticleRankingDAO(db)
	rankingRepository := repository.NewCacheArticleRankingRepository(rankingCache, rankingDAO, loggerX)
	pool, cleanup4 := ioc.InitRankingBoostPool(loggerX)
	kafkaConfig := ioc.InitKafkaConfig()
	saramaConfig := ioc.InitSaramaConfig(kafkaConfig)
	producer := ioc.InitEventProducer(kafkaConfig, saramaConfig, loggerX)
	interactionEventProducer := interaction.NewSaramaInteractionEventProducer(producer)
	interactionService := ioc.InitInteractionService(interactionServiceClient, rankingRepository, pool, interactionEventProducer, loggerX)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	commentConn, cleanup5, err := ioc.InitCommentConn(clientv3Client, prometheusBuilder)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	commentServiceClient := ioc.InitCommentClient(commentConn)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository, interactionService, commentServiceClient, loggerX)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, loggerX)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	oAuth2Service := ioc.InitWechatOAuth2Service()
	oAuth2Handler := web.NewOAuth2WechatHandler(handler, oAuth2Service, userService)
	articleSearchHandler := web.NewInternalArticleSearchHandler(articleSearchService, loggerX)
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	clickEventCache := cache.NewRedisAIClickEventCache(client)
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	clickEventHandler := web.NewAIClickEventHandler(clickEventService, loggerX)
	llmConfig := ioc.InitLLMConfig()
	llmClient := ioc.InitLLMClient(llmConfig, loggerX)
	articlePolishService := service.NewAIArticlePolishService(llmClient)
	articlePolishHandler := web.NewAIArticlePolishHandler(articlePolishService, client, loggerX)
	rankingService := service.NewArticleRankingService(rankingRepository, articleReaderRepository, interactionService, clickEventService, loggerX)
	rankingHandler := web.NewArticleRankingHandler(rankingService, loggerX)
	commentService := service.NewGRPCCommentService(commentServiceClient, interactionService, userService, loggerX)
	commentHandler := web.NewInternalCommentHandler(commentService)
	relationConn, cleanup6, err := ioc.InitRelationConn(clientv3Client, prometheusBuilder)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	relationServiceClient := ioc.InitRelationClient(relationConn)
	relationEventProducer := relation.NewSaramaRelationEventProducer(producer)
	relationService := service.NewGRPCRelationService(relationServiceClient, userService, relationEventProducer, loggerX)
	relationHandler := web.NewInternalRelationHandler(relationService)
	engine := ioc.InitWebServer(v, userHandler, articleAuthorHandler, articleReaderHandler, interactionHandler, oAuth2Handler, articleSearchHandler, clickEventHandler, articlePolishHandler, rankingHandler, commentHandler, relationHandler)
	searchServer := grpc.NewSearchServer(articleSearchService)
	articleReaderServer := grpc.NewArticleReaderServer(articleReaderService)
	rankingJobServer := grpc.NewRankingJobServer(rankingService)
	server := ioc.InitGRPCServer(searchServer, articleReaderServer, rankingJobServer, clientv3Client, prometheusBuilder, loggerX)
	app := App{
		Server:     engine,
		GRPCServer: server,
	}
	return app, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// searchProviderSet 搜索模块的 Wire Provider 集合（不含 Handler）
var searchProviderSet = wire.NewSet(ioc.InitESClient, ioc.InitOllamaEmbeddingConfig, ioc.InitEmbeddingConfig, ioc.InitEmbeddingClient, dao.NewElasticArticleDAO, repository.NewESArticleSearchRepository, service.NewArticleSearchService)

// clickEventProviderSet 点击埋点模块
var clickEventProviderSet = wire.NewSet(dao.NewGormAIClickEventDAO, cache.NewRedisAIClickEventCache, repository.NewCacheAIClickEventRepository, service.NewAIClickEventService)

// polishProviderSet 文章润色模块（含 LLM 配置/客户端 — 之前在 chatProviderSet 里）
var polishProviderSet = wire.NewSet(ioc.InitLLMConfig, ioc.InitLLMClient, service.NewAIArticlePolishService)

// articleRankingProviderSet 文章榜单模块（数据 + 重算逻辑留 core；定时调度由 webook-worker 经 RankingJobService gRPC 触发）
var articleRankingProviderSet = wire.NewSet(dao.NewGormArticleRankingDAO, cache.NewRedisArticleRankingCache, repository.NewCacheArticleRankingRepository, service.NewArticleRankingService, web.NewArticleRankingHandler, grpc.NewRankingJobServer)

// migratorSDKProviderSet 业务侧迁移 SDK（默认 NoOp 零开销，yaml migrator.sdk.enabled=true 切 Redis 实现）
var migratorSDKProviderSet = wire.NewSet(ioc.InitMigratorSDKSwitchReader, ioc.InitMigratorSDKDualWriter, ioc.InitMigratorSDKTaskName, dao.NewGormArticleReaderNewDAO)

// kafkaProviderSet Kafka 生产侧：core 只产 read 事件，消费由 webook-worker（调度器）负责。
var kafkaProviderSet = wire.NewSet(ioc.InitKafkaConfig, ioc.InitSaramaConfig, ioc.InitEventProducer, interaction.NewSaramaInteractionEventProducer, relation.NewSaramaRelationEventProducer)

// App 应用入口：Web 服务 + gRPC 服务（消费者/定时任务已抽到 webook-worker）。
type App struct {
	Server     *gin.Engine
	GRPCServer *grpcx.Server
}
