// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"

	"github.com/webook/chat/ioc"
	"github.com/webook/chat/repository"
	"github.com/webook/chat/repository/cache"
	"github.com/webook/chat/repository/dao"
	"github.com/webook/chat/service"
	"github.com/webook/chat/web"
	"github.com/webook/pkg/streamer"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	loggerX := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	tracerProvider, cleanup, err := ioc.InitOTel()
	if err != nil {
		return App{}, nil, err
	}
	v := ioc.InitMiddlewares(loggerX, cmdable, tracerProvider)
	timezoneReady := ioc.InitTimezone()
	db := ioc.InitDB(timezoneReady, loggerX)
	conversationDAO := dao.NewGormConversationDAO(db)
	conversationCache := cache.NewRedisConversationCache(cmdable)
	conversationRepository := repository.NewCacheConversationRepository(conversationDAO, conversationCache, loggerX)
	messageDAO := dao.NewGormMessageDAO(db)
	messageCache := cache.NewRedisMessageCache(cmdable)
	messageRepository := repository.NewCacheMessageRepository(messageDAO, messageCache, loggerX)
	config := ioc.InitLLMConfig()
	client := ioc.InitLLMClient(config, loggerX)
	clientv3Client, cleanup2, err := ioc.InitEtcdClient()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	prometheusBuilder := ioc.InitGRPCMetrics()
	coreConn, cleanup3, err := ioc.InitCoreConn(clientv3Client, prometheusBuilder)
	if err != nil {
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	searchServiceClient := ioc.InitSearchClient(coreConn)
	articleReaderServiceClient := ioc.InitArticleReaderClient(coreConn)
	interactionConn, cleanup4, err := ioc.InitInteractionConn(clientv3Client, prometheusBuilder)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	interactionServiceClient := ioc.InitInteractionClient(interactionConn)
	toolExecutor := service.NewAIChatToolExecutor(searchServiceClient, articleReaderServiceClient, interactionServiceClient, loggerX)
	eventStreamer := streamer.NewRedisStreamer(cmdable)
	chatService := service.NewAIChatService(conversationRepository, messageRepository, client, searchServiceClient, toolExecutor, loggerX, eventStreamer)
	limiter := ioc.InitChatLimiter(cmdable)
	chatHandler := web.NewInternalChatHandler(chatService, loggerX, limiter)
	engine := ioc.InitWebServer(v, chatHandler)
	app := App{
		Server: engine,
		Conn:   coreConn,
	}
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App chat 服务进程入口。
type App struct {
	Server *gin.Engine
	Conn   ioc.CoreConn
}
