// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/llm/types.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/llm/types.go -package=llmmocks -destination=./pkg/llm/mocks/llm_mock.go
//

// Package llmmocks is a generated GoMock package.
package llmmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	llm "github.com/webook/pkg/llm"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockClient) Chat(ctx context.Context, messages []llm.ChatMessage) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, messages)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockClientMockRecorder) Chat(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockClient)(nil).Chat), ctx, messages)
}

// ChatStream mocks base method.
func (m *MockClient) ChatStream(ctx context.Context, messages []llm.ChatMessage, tools []llm.Tool) (<-chan llm.StreamChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, messages, tools)
	ret0, _ := ret[0].(<-chan llm.StreamChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockClientMockRecorder) ChatStream(ctx, messages, tools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockClient)(nil).ChatStream), ctx, messages, tools)
}
