// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/boyxs/train-go/webook/comment/grpc"
	"github.com/boyxs/train-go/webook/comment/ioc"
	"github.com/boyxs/train-go/webook/comment/repository"
	"github.com/boyxs/train-go/webook/comment/repository/cache"
	"github.com/boyxs/train-go/webook/comment/repository/dao"
	"github.com/boyxs/train-go/webook/comment/service"
	"github.com/boyxs/train-go/webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	timezoneReady := ioc.InitTimezone()
	loggerX := ioc.InitLogger()
	db := ioc.InitDB(timezoneReady, loggerX)
	commentDAO := dao.NewGormCommentDAO(db)
	cmdable := ioc.InitRedis()
	commentCache := cache.NewRedisCommentCache(cmdable)
	commentRepository := repository.NewCacheCommentRepository(commentDAO, commentCache, loggerX)
	filter := ioc.InitSensitiveFilter()
	limiter := ioc.InitLimiter(cmdable)
	commentService := service.NewCommentService(commentRepository, filter, limiter, loggerX)
	commentServer := grpc.NewCommentServer(commentService)
	client, cleanup, err := ioc.InitEtcdClient()
	if err != nil {
		return App{}, nil, err
	}
	tracerProvider, cleanup2, err := ioc.InitOTel()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	server := ioc.InitGRPCServer(commentServer, client, loggerX, tracerProvider)
	app := App{
		GRPCServer: server,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App comment 服务进程入口（纯 gRPC server）。
type App struct {
	GRPCServer *grpcx.Server
}
