---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Liu.
--- DateTime: 26.2.11 15:21
---

local key = KEYS[1]
local cntKey = key .. ":cnt"
local val = ARGV[1]
local expire = 600

local ttl = tonumber(redis.call("ttl", key))
if ttl == -1 then
    --key存在，但没有过期时间，异常操作
    return -2
elseif ttl == -2 or ttl < (expire - 60) then
    --Key不存在 或 小于9分钟
    redis.call("set", key, val)
    redis.call("expire", key, expire)
    redis.call("set", cntKey, 3)
    redis.call("expire", cntKey, expire)
    return 0
else
    --发送太频繁
    return -1
end
