---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Liu.
--- DateTime: 26.2.11 15:22
---

local key = KEYS[1]
local cntKey = key .. ":cnt"
local val = ARGV[1]

local cnt = tonumber(redis.call("get", cntKey))
local code = redis.call("get", key)

if cnt == nil then
    --验证码不存在
    return -1
elseif cnt <= 0 then
    --次数已耗尽
    return -2
end

if val == code then
    --验证成功
    redis.call("set", cntKey, 0)
    --redis.call("del", key)
    --redis.call("del", cntKey)
    return 0
else
    --验证不匹配，扣减次数
    redis.call("decr", cntKey)
    return -3
end