// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/boyxs/train-go/webook/api/gen/comment/v1 (interfaces: CommentServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./internal/web/grpcmocks/comment_mock.go -package=grpcmocks github.com/boyxs/train-go/webook/api/gen/comment/v1 CommentServiceClient
//

// Package grpcmocks is a generated GoMock package.
package grpcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	commentv1 "github.com/boyxs/train-go/webook/api/gen/comment/v1"
)

// MockCommentServiceClient is a mock of CommentServiceClient interface.
type MockCommentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceClientMockRecorder
	isgomock struct{}
}

// MockCommentServiceClientMockRecorder is the mock recorder for MockCommentServiceClient.
type MockCommentServiceClientMockRecorder struct {
	mock *MockCommentServiceClient
}

// NewMockCommentServiceClient creates a new mock instance.
func NewMockCommentServiceClient(ctrl *gomock.Controller) *MockCommentServiceClient {
	mock := &MockCommentServiceClient{ctrl: ctrl}
	mock.recorder = &MockCommentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentServiceClient) EXPECT() *MockCommentServiceClientMockRecorder {
	return m.recorder
}

// BatchCountComment mocks base method.
func (m *MockCommentServiceClient) BatchCountComment(ctx context.Context, in *commentv1.BatchCountCommentRequest, opts ...grpc.CallOption) (*commentv1.BatchCountCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchCountComment", varargs...)
	ret0, _ := ret[0].(*commentv1.BatchCountCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCountComment indicates an expected call of BatchCountComment.
func (mr *MockCommentServiceClientMockRecorder) BatchCountComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCountComment", reflect.TypeOf((*MockCommentServiceClient)(nil).BatchCountComment), varargs...)
}

// BatchGetComments mocks base method.
func (m *MockCommentServiceClient) BatchGetComments(ctx context.Context, in *commentv1.BatchGetCommentsRequest, opts ...grpc.CallOption) (*commentv1.BatchGetCommentsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetComments", varargs...)
	ret0, _ := ret[0].(*commentv1.BatchGetCommentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetComments indicates an expected call of BatchGetComments.
func (mr *MockCommentServiceClientMockRecorder) BatchGetComments(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetComments", reflect.TypeOf((*MockCommentServiceClient)(nil).BatchGetComments), varargs...)
}

// CountComment mocks base method.
func (m *MockCommentServiceClient) CountComment(ctx context.Context, in *commentv1.CountCommentRequest, opts ...grpc.CallOption) (*commentv1.CountCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountComment", varargs...)
	ret0, _ := ret[0].(*commentv1.CountCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountComment indicates an expected call of CountComment.
func (mr *MockCommentServiceClientMockRecorder) CountComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountComment", reflect.TypeOf((*MockCommentServiceClient)(nil).CountComment), varargs...)
}

// CreateComment mocks base method.
func (m *MockCommentServiceClient) CreateComment(ctx context.Context, in *commentv1.CreateCommentRequest, opts ...grpc.CallOption) (*commentv1.CreateCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateComment", varargs...)
	ret0, _ := ret[0].(*commentv1.CreateCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentServiceClientMockRecorder) CreateComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentServiceClient)(nil).CreateComment), varargs...)
}

// DeleteComment mocks base method.
func (m *MockCommentServiceClient) DeleteComment(ctx context.Context, in *commentv1.DeleteCommentRequest, opts ...grpc.CallOption) (*commentv1.DeleteCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteComment", varargs...)
	ret0, _ := ret[0].(*commentv1.DeleteCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentServiceClientMockRecorder) DeleteComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentServiceClient)(nil).DeleteComment), varargs...)
}

// GetReplies mocks base method.
func (m *MockCommentServiceClient) GetReplies(ctx context.Context, in *commentv1.GetRepliesRequest, opts ...grpc.CallOption) (*commentv1.GetRepliesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReplies", varargs...)
	ret0, _ := ret[0].(*commentv1.GetRepliesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplies indicates an expected call of GetReplies.
func (mr *MockCommentServiceClientMockRecorder) GetReplies(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplies", reflect.TypeOf((*MockCommentServiceClient)(nil).GetReplies), varargs...)
}

// ListComments mocks base method.
func (m *MockCommentServiceClient) ListComments(ctx context.Context, in *commentv1.ListCommentsRequest, opts ...grpc.CallOption) (*commentv1.ListCommentsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListComments", varargs...)
	ret0, _ := ret[0].(*commentv1.ListCommentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockCommentServiceClientMockRecorder) ListComments(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockCommentServiceClient)(nil).ListComments), varargs...)
}
