// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/boyxs/train-go/webook/api/gen/feed/v1 (interfaces: FeedServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./web/grpcmocks/feed_mock.go -package=grpcmocks github.com/boyxs/train-go/webook/api/gen/feed/v1 FeedServiceClient
//

// Package grpcmocks is a generated GoMock package.
package grpcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	feedv1 "github.com/boyxs/train-go/webook/api/gen/feed/v1"
)

// MockFeedServiceClient is a mock of FeedServiceClient interface.
type MockFeedServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceClientMockRecorder
	isgomock struct{}
}

// MockFeedServiceClientMockRecorder is the mock recorder for MockFeedServiceClient.
type MockFeedServiceClientMockRecorder struct {
	mock *MockFeedServiceClient
}

// NewMockFeedServiceClient creates a new mock instance.
func NewMockFeedServiceClient(ctrl *gomock.Controller) *MockFeedServiceClient {
	mock := &MockFeedServiceClient{ctrl: ctrl}
	mock.recorder = &MockFeedServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedServiceClient) EXPECT() *MockFeedServiceClientMockRecorder {
	return m.recorder
}

// FanoutArticle mocks base method.
func (m *MockFeedServiceClient) FanoutArticle(ctx context.Context, in *feedv1.FanoutArticleRequest, opts ...grpc.CallOption) (*feedv1.FanoutArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FanoutArticle", varargs...)
	ret0, _ := ret[0].(*feedv1.FanoutArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FanoutArticle indicates an expected call of FanoutArticle.
func (mr *MockFeedServiceClientMockRecorder) FanoutArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FanoutArticle", reflect.TypeOf((*MockFeedServiceClient)(nil).FanoutArticle), varargs...)
}

// InvalidateInboxes mocks base method.
func (m *MockFeedServiceClient) InvalidateInboxes(ctx context.Context, in *feedv1.InvalidateInboxesRequest, opts ...grpc.CallOption) (*feedv1.InvalidateInboxesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InvalidateInboxes", varargs...)
	ret0, _ := ret[0].(*feedv1.InvalidateInboxesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvalidateInboxes indicates an expected call of InvalidateInboxes.
func (mr *MockFeedServiceClientMockRecorder) InvalidateInboxes(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateInboxes", reflect.TypeOf((*MockFeedServiceClient)(nil).InvalidateInboxes), varargs...)
}

// ListFeed mocks base method.
func (m *MockFeedServiceClient) ListFeed(ctx context.Context, in *feedv1.ListFeedRequest, opts ...grpc.CallOption) (*feedv1.ListFeedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFeed", varargs...)
	ret0, _ := ret[0].(*feedv1.ListFeedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeed indicates an expected call of ListFeed.
func (mr *MockFeedServiceClientMockRecorder) ListFeed(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeed", reflect.TypeOf((*MockFeedServiceClient)(nil).ListFeed), varargs...)
}

// NewCount mocks base method.
func (m *MockFeedServiceClient) NewCount(ctx context.Context, in *feedv1.NewCountRequest, opts ...grpc.CallOption) (*feedv1.NewCountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewCount", varargs...)
	ret0, _ := ret[0].(*feedv1.NewCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCount indicates an expected call of NewCount.
func (mr *MockFeedServiceClientMockRecorder) NewCount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCount", reflect.TypeOf((*MockFeedServiceClient)(nil).NewCount), varargs...)
}

// RemoveArticle mocks base method.
func (m *MockFeedServiceClient) RemoveArticle(ctx context.Context, in *feedv1.RemoveArticleRequest, opts ...grpc.CallOption) (*feedv1.RemoveArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveArticle", varargs...)
	ret0, _ := ret[0].(*feedv1.RemoveArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveArticle indicates an expected call of RemoveArticle.
func (mr *MockFeedServiceClientMockRecorder) RemoveArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveArticle", reflect.TypeOf((*MockFeedServiceClient)(nil).RemoveArticle), varargs...)
}
