// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/boyxs/train-go/webook/api/gen/search/v1 (interfaces: SearchServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./web/grpcmocks/search_mock.go -package=grpcmocks github.com/boyxs/train-go/webook/api/gen/search/v1 SearchServiceClient
//

// Package grpcmocks is a generated GoMock package.
package grpcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	searchv1 "github.com/boyxs/train-go/webook/api/gen/search/v1"
)

// MockSearchServiceClient is a mock of SearchServiceClient interface.
type MockSearchServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServiceClientMockRecorder
	isgomock struct{}
}

// MockSearchServiceClientMockRecorder is the mock recorder for MockSearchServiceClient.
type MockSearchServiceClientMockRecorder struct {
	mock *MockSearchServiceClient
}

// NewMockSearchServiceClient creates a new mock instance.
func NewMockSearchServiceClient(ctrl *gomock.Controller) *MockSearchServiceClient {
	mock := &MockSearchServiceClient{ctrl: ctrl}
	mock.recorder = &MockSearchServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchServiceClient) EXPECT() *MockSearchServiceClientMockRecorder {
	return m.recorder
}

// IndexArticle mocks base method.
func (m *MockSearchServiceClient) IndexArticle(ctx context.Context, in *searchv1.IndexArticleRequest, opts ...grpc.CallOption) (*searchv1.IndexArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IndexArticle", varargs...)
	ret0, _ := ret[0].(*searchv1.IndexArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexArticle indicates an expected call of IndexArticle.
func (mr *MockSearchServiceClientMockRecorder) IndexArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexArticle", reflect.TypeOf((*MockSearchServiceClient)(nil).IndexArticle), varargs...)
}

// RecommendTags mocks base method.
func (m *MockSearchServiceClient) RecommendTags(ctx context.Context, in *searchv1.RecommendTagsRequest, opts ...grpc.CallOption) (*searchv1.RecommendTagsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RecommendTags", varargs...)
	ret0, _ := ret[0].(*searchv1.RecommendTagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecommendTags indicates an expected call of RecommendTags.
func (mr *MockSearchServiceClientMockRecorder) RecommendTags(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecommendTags", reflect.TypeOf((*MockSearchServiceClient)(nil).RecommendTags), varargs...)
}

// RemoveArticle mocks base method.
func (m *MockSearchServiceClient) RemoveArticle(ctx context.Context, in *searchv1.RemoveArticleRequest, opts ...grpc.CallOption) (*searchv1.RemoveArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveArticle", varargs...)
	ret0, _ := ret[0].(*searchv1.RemoveArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveArticle indicates an expected call of RemoveArticle.
func (mr *MockSearchServiceClientMockRecorder) RemoveArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveArticle", reflect.TypeOf((*MockSearchServiceClient)(nil).RemoveArticle), varargs...)
}

// SearchArticles mocks base method.
func (m *MockSearchServiceClient) SearchArticles(ctx context.Context, in *searchv1.SearchArticlesRequest, opts ...grpc.CallOption) (*searchv1.SearchArticlesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchArticles", varargs...)
	ret0, _ := ret[0].(*searchv1.SearchArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchArticles indicates an expected call of SearchArticles.
func (mr *MockSearchServiceClientMockRecorder) SearchArticles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArticles", reflect.TypeOf((*MockSearchServiceClient)(nil).SearchArticles), varargs...)
}
