// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/boyxs/train-go/webook/api/gen/tag/v1 (interfaces: TagServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./web/grpcmocks/tag_mock.go -package=grpcmocks github.com/boyxs/train-go/webook/api/gen/tag/v1 TagServiceClient
//

// Package grpcmocks is a generated GoMock package.
package grpcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	tagv1 "github.com/boyxs/train-go/webook/api/gen/tag/v1"
)

// MockTagServiceClient is a mock of TagServiceClient interface.
type MockTagServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTagServiceClientMockRecorder
	isgomock struct{}
}

// MockTagServiceClientMockRecorder is the mock recorder for MockTagServiceClient.
type MockTagServiceClientMockRecorder struct {
	mock *MockTagServiceClient
}

// NewMockTagServiceClient creates a new mock instance.
func NewMockTagServiceClient(ctrl *gomock.Controller) *MockTagServiceClient {
	mock := &MockTagServiceClient{ctrl: ctrl}
	mock.recorder = &MockTagServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagServiceClient) EXPECT() *MockTagServiceClientMockRecorder {
	return m.recorder
}

// BatchBySlugs mocks base method.
func (m *MockTagServiceClient) BatchBySlugs(ctx context.Context, in *tagv1.BatchBySlugsRequest, opts ...grpc.CallOption) (*tagv1.TagList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchBySlugs", varargs...)
	ret0, _ := ret[0].(*tagv1.TagList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchBySlugs indicates an expected call of BatchBySlugs.
func (mr *MockTagServiceClientMockRecorder) BatchBySlugs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchBySlugs", reflect.TypeOf((*MockTagServiceClient)(nil).BatchBySlugs), varargs...)
}

// BizIdsByTag mocks base method.
func (m *MockTagServiceClient) BizIdsByTag(ctx context.Context, in *tagv1.BizIdsByTagRequest, opts ...grpc.CallOption) (*tagv1.BizIdsByTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BizIdsByTag", varargs...)
	ret0, _ := ret[0].(*tagv1.BizIdsByTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BizIdsByTag indicates an expected call of BizIdsByTag.
func (mr *MockTagServiceClientMockRecorder) BizIdsByTag(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BizIdsByTag", reflect.TypeOf((*MockTagServiceClient)(nil).BizIdsByTag), varargs...)
}

// Detail mocks base method.
func (m *MockTagServiceClient) Detail(ctx context.Context, in *tagv1.DetailRequest, opts ...grpc.CallOption) (*tagv1.Tag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Detail", varargs...)
	ret0, _ := ret[0].(*tagv1.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockTagServiceClientMockRecorder) Detail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockTagServiceClient)(nil).Detail), varargs...)
}

// Follow mocks base method.
func (m *MockTagServiceClient) Follow(ctx context.Context, in *tagv1.FollowRequest, opts ...grpc.CallOption) (*tagv1.FollowResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Follow", varargs...)
	ret0, _ := ret[0].(*tagv1.FollowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Follow indicates an expected call of Follow.
func (mr *MockTagServiceClientMockRecorder) Follow(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockTagServiceClient)(nil).Follow), varargs...)
}

// FollowStatus mocks base method.
func (m *MockTagServiceClient) FollowStatus(ctx context.Context, in *tagv1.FollowStatusRequest, opts ...grpc.CallOption) (*tagv1.FollowStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FollowStatus", varargs...)
	ret0, _ := ret[0].(*tagv1.FollowStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowStatus indicates an expected call of FollowStatus.
func (mr *MockTagServiceClientMockRecorder) FollowStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowStatus", reflect.TypeOf((*MockTagServiceClient)(nil).FollowStatus), varargs...)
}

// Suggest mocks base method.
func (m *MockTagServiceClient) Suggest(ctx context.Context, in *tagv1.SuggestRequest, opts ...grpc.CallOption) (*tagv1.TagList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Suggest", varargs...)
	ret0, _ := ret[0].(*tagv1.TagList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Suggest indicates an expected call of Suggest.
func (mr *MockTagServiceClientMockRecorder) Suggest(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suggest", reflect.TypeOf((*MockTagServiceClient)(nil).Suggest), varargs...)
}

// SyncTags mocks base method.
func (m *MockTagServiceClient) SyncTags(ctx context.Context, in *tagv1.SyncTagsRequest, opts ...grpc.CallOption) (*tagv1.TagList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SyncTags", varargs...)
	ret0, _ := ret[0].(*tagv1.TagList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncTags indicates an expected call of SyncTags.
func (mr *MockTagServiceClientMockRecorder) SyncTags(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncTags", reflect.TypeOf((*MockTagServiceClient)(nil).SyncTags), varargs...)
}

// TagsByBiz mocks base method.
func (m *MockTagServiceClient) TagsByBiz(ctx context.Context, in *tagv1.TagsByBizRequest, opts ...grpc.CallOption) (*tagv1.TagsByBizResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TagsByBiz", varargs...)
	ret0, _ := ret[0].(*tagv1.TagsByBizResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagsByBiz indicates an expected call of TagsByBiz.
func (mr *MockTagServiceClientMockRecorder) TagsByBiz(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagsByBiz", reflect.TypeOf((*MockTagServiceClient)(nil).TagsByBiz), varargs...)
}

// Unfollow mocks base method.
func (m *MockTagServiceClient) Unfollow(ctx context.Context, in *tagv1.FollowRequest, opts ...grpc.CallOption) (*tagv1.FollowResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Unfollow", varargs...)
	ret0, _ := ret[0].(*tagv1.FollowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockTagServiceClientMockRecorder) Unfollow(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockTagServiceClient)(nil).Unfollow), varargs...)
}
