// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/train-cloud/geektime-basic-go/internal/repository"
	"gitee.com/train-cloud/geektime-basic-go/internal/repository/cache"
	"gitee.com/train-cloud/geektime-basic-go/internal/repository/dao"
	"gitee.com/train-cloud/geektime-basic-go/internal/service"
	"gitee.com/train-cloud/geektime-basic-go/internal/web"
	"gitee.com/train-cloud/geektime-basic-go/internal/web/jwt"
	"gitee.com/train-cloud/geektime-basic-go/ioc"
	"github.com/gin-gonic/gin"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	jwtHandler := jwt.NewRedisJwtHandler(cmdable)
	loggerX := ioc.InitLogger()
	v := ioc.InitMiddlewares(jwtHandler, loggerX, cmdable)
	timezoneReady := ioc.InitTimezone()
	db := ioc.InitDB(timezoneReady, loggerX)
	userDAO := dao.NewGormUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewRedisUserRepository(userDAO, userCache)
	userService := service.NewInternalUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewRedisCodeRepository(codeCache)
	smsService := ioc.InitSmsService(cmdable, loggerX)
	codeService := service.NewSmsCodeService(codeRepository, smsService)
	userHandler := web.NewInternalUserHandler(jwtHandler, userService, codeService, loggerX)
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleCache, loggerX)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, loggerX)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	oAuth2Service := ioc.InitWechatOAuth2Service()
	oAuth2Handler := web.NewOAuth2WechatHandler(jwtHandler, oAuth2Service, userService)
	engine := ioc.InitWebServer(v, userHandler, articleAuthorHandler, articleReaderHandler, interactionHandler, oAuth2Handler)
	return engine
}
