// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/webook/internal/events"
	"github.com/webook/internal/events/interaction"
	"github.com/webook/internal/repository"
	"github.com/webook/internal/repository/cache"
	"github.com/webook/internal/repository/dao"
	"github.com/webook/internal/service"
	"github.com/webook/internal/web"
	"github.com/webook/internal/web/jwt"
	"github.com/webook/ioc"
	"github.com/webook/pkg/streamer"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer() App {
	cmdable := ioc.InitRedis()
	jwtHandler := jwt.NewRedisJwtHandler(cmdable)
	loggerX := ioc.InitLogger()
	v := ioc.InitMiddlewares(jwtHandler, loggerX, cmdable)
	timezoneReady := ioc.InitTimezone()
	db := ioc.InitDB(timezoneReady, loggerX)
	userDAO := dao.NewGormUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewRedisUserRepository(userDAO, userCache)
	userService := service.NewInternalUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewRedisCodeRepository(codeCache)
	smsService := ioc.InitSmsService(cmdable, loggerX)
	codeService := service.NewSmsCodeService(codeRepository, smsService)
	userHandler := web.NewInternalUserHandler(jwtHandler, userService, codeService, loggerX)
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleCache, loggerX)
	typedClient := ioc.InitESClient()
	articleSearchDAO := dao.NewElasticArticleDAO(typedClient)
	articleSearchRepository := repository.NewESArticleSearchRepository(articleSearchDAO)
	ollamaEmbeddingConfig := ioc.InitOllamaEmbeddingConfig()
	embeddingConfig := ioc.InitEmbeddingConfig()
	embeddingClient := ioc.InitEmbeddingClient(ollamaEmbeddingConfig, embeddingConfig, cmdable, loggerX)
	articleSearchService := service.NewArticleSearchService(articleSearchRepository, embeddingClient, loggerX)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository, articleSearchService, loggerX)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	kafkaConfig := ioc.InitKafkaConfig()
	config := ioc.InitSaramaConfig(kafkaConfig)
	syncProducer := ioc.InitSaramaSyncProducer(kafkaConfig, config)
	producer := ioc.InitEventProducer(syncProducer, loggerX)
	interactionEventProducer := interaction.NewSaramaInteractionEventProducer(producer)
	interactionService := ioc.InitInteractionService(interactionRepository, interactionEventProducer, loggerX)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, loggerX)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	oAuth2Service := ioc.InitWechatOAuth2Service()
	oAuth2Handler := web.NewOAuth2WechatHandler(jwtHandler, oAuth2Service, userService)
	conversationDAO := dao.NewGormConversationDAO(db)
	conversationCache := cache.NewRedisConversationCache(cmdable)
	conversationRepository := repository.NewCacheConversationRepository(conversationDAO, conversationCache, loggerX)
	messageDAO := dao.NewGormMessageDAO(db)
	messageCache := cache.NewRedisMessageCache(cmdable)
	messageRepository := repository.NewCacheMessageRepository(messageDAO, messageCache, loggerX)
	llmConfig := ioc.InitLLMConfig()
	llmClient := ioc.InitLLMClient(llmConfig, loggerX)
	toolExecutor := service.NewAIChatToolExecutor(articleSearchService, articleReaderService, interactionRepository, loggerX)
	eventStreamer := streamer.NewRedisStreamer(cmdable)
	chatService := service.NewAIChatService(conversationRepository, messageRepository, llmClient, articleSearchService, toolExecutor, loggerX, eventStreamer)
	limiter := ioc.InitChatLimiter(cmdable)
	chatHandler := web.NewInternalChatHandler(chatService, loggerX, limiter)
	articleSearchHandler := web.NewInternalArticleSearchHandler(articleSearchService, loggerX)
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	clickEventCache := cache.NewRedisAIClickEventCache(cmdable)
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	clickEventHandler := web.NewAIClickEventHandler(clickEventService, loggerX)
	articlePolishService := service.NewAIArticlePolishService(llmClient)
	articlePolishHandler := web.NewAIArticlePolishHandler(articlePolishService, cmdable, loggerX)
	engine := ioc.InitWebServer(v, userHandler, articleAuthorHandler, articleReaderHandler, interactionHandler, oAuth2Handler, chatHandler, articleSearchHandler, clickEventHandler, articlePolishHandler)
	client := ioc.InitSaramaClient(kafkaConfig, config)
	consumerConfig := ioc.InitInteractionConsumerConfig(kafkaConfig)
	consumer := interaction.NewSaramaInteractionEventConsumer(client, interactionRepository, consumerConfig, loggerX)
	app := App{
		Server:   engine,
		Consumer: consumer,
	}
	return app
}

// wire.go:

// searchProviderSet 搜索模块的 Wire Provider 集合（不含 Handler）
var searchProviderSet = wire.NewSet(ioc.InitESClient, ioc.InitOllamaEmbeddingConfig, ioc.InitEmbeddingConfig, ioc.InitEmbeddingClient, dao.NewElasticArticleDAO, repository.NewESArticleSearchRepository, service.NewArticleSearchService)

// clickEventProviderSet 点击埋点模块
var clickEventProviderSet = wire.NewSet(dao.NewGormAIClickEventDAO, cache.NewRedisAIClickEventCache, repository.NewCacheAIClickEventRepository, service.NewAIClickEventService)

// polishProviderSet 文章润色模块
var polishProviderSet = wire.NewSet(service.NewAIArticlePolishService)

// kafkaProviderSet Kafka 基础设施 + 互动事件
var kafkaProviderSet = wire.NewSet(ioc.InitKafkaConfig, ioc.InitSaramaConfig, ioc.InitSaramaSyncProducer, ioc.InitSaramaClient, ioc.InitEventProducer, ioc.InitInteractionConsumerConfig, interaction.NewSaramaInteractionEventProducer, interaction.NewSaramaInteractionEventConsumer)

// chatProviderSet Chat 模块的 Wire Provider 集合（不含 Handler）
var chatProviderSet = wire.NewSet(ioc.InitLLMConfig, ioc.InitLLMClient, ioc.InitChatLimiter, dao.NewGormConversationDAO, dao.NewGormMessageDAO, cache.NewRedisConversationCache, cache.NewRedisMessageCache, repository.NewCacheConversationRepository, repository.NewCacheMessageRepository, service.NewAIChatService, service.NewAIChatToolExecutor, streamer.NewRedisStreamer)

// App 应用入口，包含 Web 服务和后台消费者
type App struct {
	Server   *gin.Engine
	Consumer events.Consumer
}
