// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/boyxs/train-go/webook/pkg/grpcx"
	"github.com/boyxs/train-go/webook/tag/grpc"
	"github.com/boyxs/train-go/webook/tag/ioc"
	"github.com/boyxs/train-go/webook/tag/repository"
	"github.com/boyxs/train-go/webook/tag/repository/cache"
	"github.com/boyxs/train-go/webook/tag/repository/dao"
	"github.com/boyxs/train-go/webook/tag/service"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	timezoneReady := ioc.InitTimezone()
	loggerX := ioc.InitLogger()
	db := ioc.InitDB(timezoneReady, loggerX)
	tagDAO := dao.NewGormTagDAO(db)
	taggingDAO := dao.NewGormTaggingDAO(db)
	tagFollowDAO := dao.NewGormTagFollowDAO(db)
	cmdable := ioc.InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	tagRepository := repository.NewInternalTagRepository(tagDAO, taggingDAO, tagFollowDAO, tagCache, loggerX)
	tagService := service.NewInternalTagService(tagRepository)
	tagServer := grpc.NewTagServer(tagService)
	client, cleanup, err := ioc.InitEtcdClient()
	if err != nil {
		return App{}, nil, err
	}
	tracerProvider, cleanup2, err := ioc.InitOTel()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	server := ioc.InitGRPCServer(tagServer, client, loggerX, tracerProvider)
	app := App{
		GRPCServer: server,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App tag 服务进程入口（纯 gRPC server）。
type App struct {
	GRPCServer *grpcx.Server
}
