// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/webook/interaction/grpc"
	"github.com/webook/interaction/ioc"
	"github.com/webook/interaction/repository"
	"github.com/webook/interaction/repository/cache"
	"github.com/webook/interaction/repository/dao"
	"github.com/webook/interaction/service"
	"github.com/webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	timezoneReady := ioc.InitTimezone()
	loggerX := ioc.InitLogger()
	db := ioc.InitDB(timezoneReady, loggerX)
	interactionDAO := dao.NewGormInteractionDAO(db)
	cmdable := ioc.InitRedis()
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	interactionServer := grpc.NewInteractionServer(interactionService)
	client, cleanup, err := ioc.InitEtcdClient()
	if err != nil {
		return App{}, nil, err
	}
	tracerProvider, cleanup2, err := ioc.InitOTel()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	server := ioc.InitGRPCServer(interactionServer, client, loggerX, tracerProvider)
	app := App{
		GRPCServer: server,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App interaction 服务进程入口（纯 gRPC server）。
type App struct {
	GRPCServer *grpcx.Server
}
