// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/cache/click_event.go
//
// Generated by this command:
//
//	mockgen -source=./repository/cache/click_event.go -package=cachemocks -destination=./repository/cache/mocks/click_event_mock.go
//

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/internal/domain"
)

// MockClickEventCache is a mock of ClickEventCache interface.
type MockClickEventCache struct {
	ctrl     *gomock.Controller
	recorder *MockClickEventCacheMockRecorder
	isgomock struct{}
}

// MockClickEventCacheMockRecorder is the mock recorder for MockClickEventCache.
type MockClickEventCacheMockRecorder struct {
	mock *MockClickEventCache
}

// NewMockClickEventCache creates a new mock instance.
func NewMockClickEventCache(ctrl *gomock.Controller) *MockClickEventCache {
	mock := &MockClickEventCache{ctrl: ctrl}
	mock.recorder = &MockClickEventCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickEventCache) EXPECT() *MockClickEventCacheMockRecorder {
	return m.recorder
}

// DelDashboard mocks base method.
func (m *MockClickEventCache) DelDashboard(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelDashboard", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelDashboard indicates an expected call of DelDashboard.
func (mr *MockClickEventCacheMockRecorder) DelDashboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelDashboard", reflect.TypeOf((*MockClickEventCache)(nil).DelDashboard), ctx)
}

// GetDashboard mocks base method.
func (m *MockClickEventCache) GetDashboard(ctx context.Context) (domain.ClickEventDashboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboard", ctx)
	ret0, _ := ret[0].(domain.ClickEventDashboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboard indicates an expected call of GetDashboard.
func (mr *MockClickEventCacheMockRecorder) GetDashboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboard", reflect.TypeOf((*MockClickEventCache)(nil).GetDashboard), ctx)
}

// SetDashboard mocks base method.
func (m *MockClickEventCache) SetDashboard(ctx context.Context, data domain.ClickEventDashboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDashboard", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDashboard indicates an expected call of SetDashboard.
func (mr *MockClickEventCacheMockRecorder) SetDashboard(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDashboard", reflect.TypeOf((*MockClickEventCache)(nil).SetDashboard), ctx, data)
}
