// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/cache/ranking.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/cache/ranking.go -package=cachemocks -destination=./internal/repository/cache/mocks/ranking_mock.go
//

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockRankingCache is a mock of RankingCache interface.
type MockRankingCache struct {
	ctrl     *gomock.Controller
	recorder *MockRankingCacheMockRecorder
	isgomock struct{}
}

// MockRankingCacheMockRecorder is the mock recorder for MockRankingCache.
type MockRankingCacheMockRecorder struct {
	mock *MockRankingCache
}

// NewMockRankingCache creates a new mock instance.
func NewMockRankingCache(ctrl *gomock.Controller) *MockRankingCache {
	mock := &MockRankingCache{ctrl: ctrl}
	mock.recorder = &MockRankingCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingCache) EXPECT() *MockRankingCacheMockRecorder {
	return m.recorder
}

// DelDay mocks base method.
func (m *MockRankingCache) DelDay(ctx context.Context, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelDay", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelDay indicates an expected call of DelDay.
func (mr *MockRankingCacheMockRecorder) DelDay(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelDay", reflect.TypeOf((*MockRankingCache)(nil).DelDay), ctx, date)
}

// GetDetails mocks base method.
func (m *MockRankingCache) GetDetails(ctx context.Context, date string, articleIds []int64) (map[int64]domain.ArticleRanking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", ctx, date, articleIds)
	ret0, _ := ret[0].(map[int64]domain.ArticleRanking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockRankingCacheMockRecorder) GetDetails(ctx, date, articleIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockRankingCache)(nil).GetDetails), ctx, date, articleIds)
}

// GetPrevRanks mocks base method.
func (m *MockRankingCache) GetPrevRanks(ctx context.Context, date, dim, cat string, articleIds []int64) (map[int64]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrevRanks", ctx, date, dim, cat, articleIds)
	ret0, _ := ret[0].(map[int64]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrevRanks indicates an expected call of GetPrevRanks.
func (mr *MockRankingCacheMockRecorder) GetPrevRanks(ctx, date, dim, cat, articleIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrevRanks", reflect.TypeOf((*MockRankingCache)(nil).GetPrevRanks), ctx, date, dim, cat, articleIds)
}

// IncrScore mocks base method.
func (m *MockRankingCache) IncrScore(ctx context.Context, date, dim, cat string, articleId int64, delta float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrScore", ctx, date, dim, cat, articleId, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrScore indicates an expected call of IncrScore.
func (mr *MockRankingCacheMockRecorder) IncrScore(ctx, date, dim, cat, articleId, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrScore", reflect.TypeOf((*MockRankingCache)(nil).IncrScore), ctx, date, dim, cat, articleId, delta)
}

// ReplaceTop mocks base method.
func (m *MockRankingCache) ReplaceTop(ctx context.Context, date, dim, cat string, items []domain.ArticleRanking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTop", ctx, date, dim, cat, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTop indicates an expected call of ReplaceTop.
func (mr *MockRankingCacheMockRecorder) ReplaceTop(ctx, date, dim, cat, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTop", reflect.TypeOf((*MockRankingCache)(nil).ReplaceTop), ctx, date, dim, cat, items)
}

// SetDetails mocks base method.
func (m *MockRankingCache) SetDetails(ctx context.Context, date string, details map[int64]domain.ArticleRanking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDetails", ctx, date, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDetails indicates an expected call of SetDetails.
func (mr *MockRankingCacheMockRecorder) SetDetails(ctx, date, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDetails", reflect.TypeOf((*MockRankingCache)(nil).SetDetails), ctx, date, details)
}

// SnapshotRanks mocks base method.
func (m *MockRankingCache) SnapshotRanks(ctx context.Context, date, dim, cat string, ranks map[int64]int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotRanks", ctx, date, dim, cat, ranks)
	ret0, _ := ret[0].(error)
	return ret0
}

// SnapshotRanks indicates an expected call of SnapshotRanks.
func (mr *MockRankingCacheMockRecorder) SnapshotRanks(ctx, date, dim, cat, ranks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotRanks", reflect.TypeOf((*MockRankingCache)(nil).SnapshotRanks), ctx, date, dim, cat, ranks)
}

// Top mocks base method.
func (m *MockRankingCache) Top(ctx context.Context, date, dim, cat string, limit int) ([]domain.ArticleRanking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Top", ctx, date, dim, cat, limit)
	ret0, _ := ret[0].([]domain.ArticleRanking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Top indicates an expected call of Top.
func (mr *MockRankingCacheMockRecorder) Top(ctx, date, dim, cat, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Top", reflect.TypeOf((*MockRankingCache)(nil).Top), ctx, date, dim, cat, limit)
}
