// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/boyxs/train-go/webook/comment/grpc"
	"github.com/boyxs/train-go/webook/comment/ioc"
	"github.com/boyxs/train-go/webook/comment/repository"
	"github.com/boyxs/train-go/webook/comment/repository/cache"
	"github.com/boyxs/train-go/webook/comment/repository/dao"
	"github.com/boyxs/train-go/webook/comment/service"
)

// Injectors from wire.go:

// InitCommentServer 组装真 dao/cache/repository/service 的 CommentServer，
// 由集成测试注册到 bufconn gRPC server，发真实请求打通全链路。
// 基础设施走本包 InitDB/InitRedis/InitLogger（连测试库），与 internal/integration/setup 同构。
func InitCommentServer() *grpc.CommentServer {
	db := InitDB()
	commentDAO := dao.NewGormCommentDAO(db)
	cmdable := InitRedis()
	commentCache := cache.NewRedisCommentCache(cmdable)
	loggerX := InitLogger()
	commentRepository := repository.NewCacheCommentRepository(commentDAO, commentCache, loggerX)
	filter := ioc.InitSensitiveFilter()
	limiter := ioc.InitLimiter(cmdable)
	commentService := service.NewCommentService(commentRepository, filter, limiter, loggerX)
	commentServer := grpc.NewCommentServer(commentService)
	return commentServer
}
