// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/boyxs/train-go/webook/search/grpc"
	"github.com/boyxs/train-go/webook/search/repository"
	"github.com/boyxs/train-go/webook/search/service"
)

// Injectors from wire.go:

// InitSearchServer 组装真 ES dao/repository/service（+ stub embedder）的 SearchServer，
// 供集成测试注册到 bufconn gRPC server，经 SearchServiceClient 发真实请求打通全链路。
// embedding 走 stub（InitStubEmbedder，文本相关确定向量），不调外部 API。
func InitSearchServer() *grpc.SearchServer {
	typedClient := InitESClient()
	loggerX := InitLogger()
	articleDAO := InitArticleDAO(typedClient, loggerX)
	articleRepository := repository.NewESArticleRepository(articleDAO)
	embedder := InitStubEmbedder()
	articleService := service.NewInternalArticleService(articleRepository, embedder, loggerX)
	searchServer := grpc.NewSearchServer(articleService)
	return searchServer
}
