// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/boyxs/train-go/webook/tag/grpc"
	"github.com/boyxs/train-go/webook/tag/repository"
	"github.com/boyxs/train-go/webook/tag/repository/cache"
	"github.com/boyxs/train-go/webook/tag/repository/dao"
	"github.com/boyxs/train-go/webook/tag/service"
)

// Injectors from wire.go:

// InitTagServer 组装真 dao/repository/service 的 TagServer，供集成测试注册到 bufconn gRPC server，
// 经 TagServiceClient 发真实请求打通 gRPC → service → repository → dao → MySQL 全链路。
// 基础设施走本包 InitDB（连测试库 webook_test），与 interaction/comment integration/setup 同构。
func InitTagServer() *grpc.TagServer {
	db := InitDB()
	tagDAO := dao.NewGormTagDAO(db)
	taggingDAO := dao.NewGormTaggingDAO(db)
	tagFollowDAO := dao.NewGormTagFollowDAO(db)
	cmdable := InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	loggerX := InitLogger()
	tagRepository := repository.NewInternalTagRepository(tagDAO, taggingDAO, tagFollowDAO, tagCache, loggerX)
	tagService := service.NewInternalTagService(tagRepository)
	tagServer := grpc.NewTagServer(tagService)
	return tagServer
}
