// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/boyxs/train-go/webook/feed/grpc"
	"github.com/boyxs/train-go/webook/feed/repository"
	"github.com/boyxs/train-go/webook/feed/repository/cache"
	"github.com/boyxs/train-go/webook/feed/service"
)

// Injectors from wire.go:

// InitFeedServer 组装真 cache/repository/service 的 FeedServer（真实 Redis + fake relation/article gRPC client），
// 供集成测试注册到 bufconn，经 FeedServiceClient 发真实请求打通 gRPC → service → repository → cache → Redis。
func InitFeedServer() *grpc.FeedServer {
	cmdable := InitRedis()
	config := InitCacheConfig()
	feedCache := cache.NewRedisFeedCache(cmdable, config)
	feedRepository := repository.NewCacheFeedRepository(feedCache)
	relationServiceClient := NewFakeRelationClient()
	articleReaderServiceClient := NewFakeArticleClient()
	serviceConfig := InitServiceConfig()
	loggerX := InitLogger()
	feedService := service.NewInternalFeedService(feedRepository, relationServiceClient, articleReaderServiceClient, serviceConfig, loggerX)
	feedServer := grpc.NewFeedServer(feedService)
	return feedServer
}
