// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/dao/article_reader.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/dao/article_reader.go -package=daomocks -destination=./internal/repository/dao/mocks/article_reader_mock.go
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	dao "github.com/webook/internal/repository/dao"
)

// MockArticleReaderDAO is a mock of ArticleReaderDAO interface.
type MockArticleReaderDAO struct {
	ctrl     *gomock.Controller
	recorder *MockArticleReaderDAOMockRecorder
	isgomock struct{}
}

// MockArticleReaderDAOMockRecorder is the mock recorder for MockArticleReaderDAO.
type MockArticleReaderDAOMockRecorder struct {
	mock *MockArticleReaderDAO
}

// NewMockArticleReaderDAO creates a new mock instance.
func NewMockArticleReaderDAO(ctrl *gomock.Controller) *MockArticleReaderDAO {
	mock := &MockArticleReaderDAO{ctrl: ctrl}
	mock.recorder = &MockArticleReaderDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleReaderDAO) EXPECT() *MockArticleReaderDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockArticleReaderDAO) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockArticleReaderDAOMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockArticleReaderDAO)(nil).Count), ctx)
}

// Delete mocks base method.
func (m *MockArticleReaderDAO) Delete(ctx context.Context, id, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArticleReaderDAOMockRecorder) Delete(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticleReaderDAO)(nil).Delete), ctx, id, uid)
}

// FindById mocks base method.
func (m *MockArticleReaderDAO) FindById(ctx context.Context, id int64) (dao.PublishedArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(dao.PublishedArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockArticleReaderDAOMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockArticleReaderDAO)(nil).FindById), ctx, id)
}

// FindByIds mocks base method.
func (m *MockArticleReaderDAO) FindByIds(ctx context.Context, ids []int64) ([]dao.PublishedArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIds", ctx, ids)
	ret0, _ := ret[0].([]dao.PublishedArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIds indicates an expected call of FindByIds.
func (mr *MockArticleReaderDAOMockRecorder) FindByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIds", reflect.TypeOf((*MockArticleReaderDAO)(nil).FindByIds), ctx, ids)
}

// Page mocks base method.
func (m *MockArticleReaderDAO) Page(ctx context.Context, offset, limit int) ([]dao.PublishedArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Page", ctx, offset, limit)
	ret0, _ := ret[0].([]dao.PublishedArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Page indicates an expected call of Page.
func (mr *MockArticleReaderDAOMockRecorder) Page(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Page", reflect.TypeOf((*MockArticleReaderDAO)(nil).Page), ctx, offset, limit)
}

// Upsert mocks base method.
func (m *MockArticleReaderDAO) Upsert(ctx context.Context, article dao.PublishedArticle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockArticleReaderDAOMockRecorder) Upsert(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockArticleReaderDAO)(nil).Upsert), ctx, article)
}
