// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/dao/article_author.go
//
// Generated by this command:
//
//	mockgen -source=./repository/dao/article_author.go -package=daomocks -destination=./repository/dao/mocks/article_author_mock.go
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	dao "github.com/boyxs/train-go/webook/internal/repository/dao"
)

// MockArticleAuthorDAO is a mock of ArticleAuthorDAO interface.
type MockArticleAuthorDAO struct {
	ctrl     *gomock.Controller
	recorder *MockArticleAuthorDAOMockRecorder
	isgomock struct{}
}

// MockArticleAuthorDAOMockRecorder is the mock recorder for MockArticleAuthorDAO.
type MockArticleAuthorDAOMockRecorder struct {
	mock *MockArticleAuthorDAO
}

// NewMockArticleAuthorDAO creates a new mock instance.
func NewMockArticleAuthorDAO(ctrl *gomock.Controller) *MockArticleAuthorDAO {
	mock := &MockArticleAuthorDAO{ctrl: ctrl}
	mock.recorder = &MockArticleAuthorDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleAuthorDAO) EXPECT() *MockArticleAuthorDAOMockRecorder {
	return m.recorder
}

// CountByAuthor mocks base method.
func (m *MockArticleAuthorDAO) CountByAuthor(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByAuthor", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByAuthor indicates an expected call of CountByAuthor.
func (mr *MockArticleAuthorDAOMockRecorder) CountByAuthor(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByAuthor", reflect.TypeOf((*MockArticleAuthorDAO)(nil).CountByAuthor), ctx, uid)
}

// Delete mocks base method.
func (m *MockArticleAuthorDAO) Delete(ctx context.Context, id, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArticleAuthorDAOMockRecorder) Delete(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticleAuthorDAO)(nil).Delete), ctx, id, uid)
}

// FindByIdAndAuthor mocks base method.
func (m *MockArticleAuthorDAO) FindByIdAndAuthor(ctx context.Context, id, uid int64) (dao.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdAndAuthor", ctx, id, uid)
	ret0, _ := ret[0].(dao.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdAndAuthor indicates an expected call of FindByIdAndAuthor.
func (mr *MockArticleAuthorDAOMockRecorder) FindByIdAndAuthor(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdAndAuthor", reflect.TypeOf((*MockArticleAuthorDAO)(nil).FindByIdAndAuthor), ctx, id, uid)
}

// Insert mocks base method.
func (m *MockArticleAuthorDAO) Insert(ctx context.Context, article dao.Article) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, article)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockArticleAuthorDAOMockRecorder) Insert(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockArticleAuthorDAO)(nil).Insert), ctx, article)
}

// ListByAuthor mocks base method.
func (m *MockArticleAuthorDAO) ListByAuthor(ctx context.Context, uid int64) ([]dao.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAuthor", ctx, uid)
	ret0, _ := ret[0].([]dao.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAuthor indicates an expected call of ListByAuthor.
func (mr *MockArticleAuthorDAOMockRecorder) ListByAuthor(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAuthor", reflect.TypeOf((*MockArticleAuthorDAO)(nil).ListByAuthor), ctx, uid)
}

// PageByAuthor mocks base method.
func (m *MockArticleAuthorDAO) PageByAuthor(ctx context.Context, uid int64, offset, limit int) ([]dao.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PageByAuthor", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]dao.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PageByAuthor indicates an expected call of PageByAuthor.
func (mr *MockArticleAuthorDAOMockRecorder) PageByAuthor(ctx, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PageByAuthor", reflect.TypeOf((*MockArticleAuthorDAO)(nil).PageByAuthor), ctx, uid, offset, limit)
}

// Update mocks base method.
func (m *MockArticleAuthorDAO) Update(ctx context.Context, article dao.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockArticleAuthorDAOMockRecorder) Update(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArticleAuthorDAO)(nil).Update), ctx, article)
}

// UpdateStatus mocks base method.
func (m *MockArticleAuthorDAO) UpdateStatus(ctx context.Context, id, uid int64, fromStatus, toStatus uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, uid, fromStatus, toStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockArticleAuthorDAOMockRecorder) UpdateStatus(ctx, id, uid, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockArticleAuthorDAO)(nil).UpdateStatus), ctx, id, uid, fromStatus, toStatus)
}
