// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/dao/click_event.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/dao/click_event.go -package=daomocks -destination=./internal/repository/dao/mocks/click_event_mock.go
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	dao "github.com/webook/internal/repository/dao"
)

// MockClickEventDAO is a mock of ClickEventDAO interface.
type MockClickEventDAO struct {
	ctrl     *gomock.Controller
	recorder *MockClickEventDAOMockRecorder
	isgomock struct{}
}

// MockClickEventDAOMockRecorder is the mock recorder for MockClickEventDAO.
type MockClickEventDAOMockRecorder struct {
	mock *MockClickEventDAO
}

// NewMockClickEventDAO creates a new mock instance.
func NewMockClickEventDAO(ctrl *gomock.Controller) *MockClickEventDAO {
	mock := &MockClickEventDAO{ctrl: ctrl}
	mock.recorder = &MockClickEventDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickEventDAO) EXPECT() *MockClickEventDAOMockRecorder {
	return m.recorder
}

// Dashboard mocks base method.
func (m *MockClickEventDAO) Dashboard(ctx context.Context, startMs int64, source string) (dao.ClickEventStats, []dao.ClickEventDailyTrend, []dao.ClickEventTopArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dashboard", ctx, startMs, source)
	ret0, _ := ret[0].(dao.ClickEventStats)
	ret1, _ := ret[1].([]dao.ClickEventDailyTrend)
	ret2, _ := ret[2].([]dao.ClickEventTopArticle)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Dashboard indicates an expected call of Dashboard.
func (mr *MockClickEventDAOMockRecorder) Dashboard(ctx, startMs, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dashboard", reflect.TypeOf((*MockClickEventDAO)(nil).Dashboard), ctx, startMs, source)
}

// Insert mocks base method.
func (m *MockClickEventDAO) Insert(ctx context.Context, event dao.ClickEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockClickEventDAOMockRecorder) Insert(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockClickEventDAO)(nil).Insert), ctx, event)
}
