// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/dao/ranking.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/dao/ranking.go -package=daomocks -destination=./internal/repository/dao/mocks/ranking_mock.go
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	dao "github.com/boyxs/train-go/webook/internal/repository/dao"
)

// MockRankingDAO is a mock of RankingDAO interface.
type MockRankingDAO struct {
	ctrl     *gomock.Controller
	recorder *MockRankingDAOMockRecorder
	isgomock struct{}
}

// MockRankingDAOMockRecorder is the mock recorder for MockRankingDAO.
type MockRankingDAOMockRecorder struct {
	mock *MockRankingDAO
}

// NewMockRankingDAO creates a new mock instance.
func NewMockRankingDAO(ctrl *gomock.Controller) *MockRankingDAO {
	mock := &MockRankingDAO{ctrl: ctrl}
	mock.recorder = &MockRankingDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingDAO) EXPECT() *MockRankingDAOMockRecorder {
	return m.recorder
}

// InsertSnapshot mocks base method.
func (m *MockRankingDAO) InsertSnapshot(ctx context.Context, date, dim, cat string, items []dao.ArticleRanking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSnapshot", ctx, date, dim, cat, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSnapshot indicates an expected call of InsertSnapshot.
func (mr *MockRankingDAOMockRecorder) InsertSnapshot(ctx, date, dim, cat, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSnapshot", reflect.TypeOf((*MockRankingDAO)(nil).InsertSnapshot), ctx, date, dim, cat, items)
}

// ListArchiveDates mocks base method.
func (m *MockRankingDAO) ListArchiveDates(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArchiveDates", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArchiveDates indicates an expected call of ListArchiveDates.
func (mr *MockRankingDAOMockRecorder) ListArchiveDates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArchiveDates", reflect.TypeOf((*MockRankingDAO)(nil).ListArchiveDates), ctx)
}

// ListByDate mocks base method.
func (m *MockRankingDAO) ListByDate(ctx context.Context, date, dim, cat string) ([]dao.ArticleRanking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDate", ctx, date, dim, cat)
	ret0, _ := ret[0].([]dao.ArticleRanking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDate indicates an expected call of ListByDate.
func (mr *MockRankingDAOMockRecorder) ListByDate(ctx, date, dim, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDate", reflect.TypeOf((*MockRankingDAO)(nil).ListByDate), ctx, date, dim, cat)
}
