// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/article_search.go
//
// Generated by this command:
//
//	mockgen -source=./service/article_search.go -package=svcmocks -destination=./service/mocks/article_search_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/internal/domain"
)

// MockArticleSearchService is a mock of ArticleSearchService interface.
type MockArticleSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockArticleSearchServiceMockRecorder
	isgomock struct{}
}

// MockArticleSearchServiceMockRecorder is the mock recorder for MockArticleSearchService.
type MockArticleSearchServiceMockRecorder struct {
	mock *MockArticleSearchService
}

// NewMockArticleSearchService creates a new mock instance.
func NewMockArticleSearchService(ctrl *gomock.Controller) *MockArticleSearchService {
	mock := &MockArticleSearchService{ctrl: ctrl}
	mock.recorder = &MockArticleSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleSearchService) EXPECT() *MockArticleSearchServiceMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MockArticleSearchService) Index(ctx context.Context, article domain.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockArticleSearchServiceMockRecorder) Index(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockArticleSearchService)(nil).Index), ctx, article)
}

// Remove mocks base method.
func (m *MockArticleSearchService) Remove(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockArticleSearchServiceMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockArticleSearchService)(nil).Remove), ctx, id)
}

// Search mocks base method.
func (m *MockArticleSearchService) Search(ctx context.Context, query string, filterTags []string, page, size int) (domain.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, filterTags, page, size)
	ret0, _ := ret[0].(domain.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockArticleSearchServiceMockRecorder) Search(ctx, query, filterTags, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockArticleSearchService)(nil).Search), ctx, query, filterTags, page, size)
}
