// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/article_search.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/article_search.go -package=svcmocks -destination=./internal/service/mocks/article_search_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockArticleSearchService is a mock of ArticleSearchService interface.
type MockArticleSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockArticleSearchServiceMockRecorder
	isgomock struct{}
}

// MockArticleSearchServiceMockRecorder is the mock recorder for MockArticleSearchService.
type MockArticleSearchServiceMockRecorder struct {
	mock *MockArticleSearchService
}

// NewMockArticleSearchService creates a new mock instance.
func NewMockArticleSearchService(ctrl *gomock.Controller) *MockArticleSearchService {
	mock := &MockArticleSearchService{ctrl: ctrl}
	mock.recorder = &MockArticleSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleSearchService) EXPECT() *MockArticleSearchServiceMockRecorder {
	return m.recorder
}

// IndexArticle mocks base method.
func (m *MockArticleSearchService) IndexArticle(ctx context.Context, article domain.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexArticle", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexArticle indicates an expected call of IndexArticle.
func (mr *MockArticleSearchServiceMockRecorder) IndexArticle(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexArticle", reflect.TypeOf((*MockArticleSearchService)(nil).IndexArticle), ctx, article)
}

// RemoveArticle mocks base method.
func (m *MockArticleSearchService) RemoveArticle(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveArticle", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveArticle indicates an expected call of RemoveArticle.
func (mr *MockArticleSearchServiceMockRecorder) RemoveArticle(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveArticle", reflect.TypeOf((*MockArticleSearchService)(nil).RemoveArticle), ctx, id)
}

// Search mocks base method.
func (m *MockArticleSearchService) Search(ctx context.Context, query string, page, size int) ([]domain.Article, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, page, size)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockArticleSearchServiceMockRecorder) Search(ctx, query, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockArticleSearchService)(nil).Search), ctx, query, page, size)
}
