// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/article_polish.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/article_polish.go -package=svcmocks -destination=./internal/service/mocks/article_polish_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockArticlePolishService is a mock of ArticlePolishService interface.
type MockArticlePolishService struct {
	ctrl     *gomock.Controller
	recorder *MockArticlePolishServiceMockRecorder
	isgomock struct{}
}

// MockArticlePolishServiceMockRecorder is the mock recorder for MockArticlePolishService.
type MockArticlePolishServiceMockRecorder struct {
	mock *MockArticlePolishService
}

// NewMockArticlePolishService creates a new mock instance.
func NewMockArticlePolishService(ctrl *gomock.Controller) *MockArticlePolishService {
	mock := &MockArticlePolishService{ctrl: ctrl}
	mock.recorder = &MockArticlePolishServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticlePolishService) EXPECT() *MockArticlePolishServiceMockRecorder {
	return m.recorder
}

// Polish mocks base method.
func (m *MockArticlePolishService) Polish(ctx context.Context, title, content string) (domain.PolishResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Polish", ctx, title, content)
	ret0, _ := ret[0].(domain.PolishResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Polish indicates an expected call of Polish.
func (mr *MockArticlePolishServiceMockRecorder) Polish(ctx, title, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Polish", reflect.TypeOf((*MockArticlePolishService)(nil).Polish), ctx, title, content)
}
