// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/article.go
//
// Generated by this command:
//
//	mockgen -source=./service/article.go -package=svcmocks -destination=./service/mocks/article_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/internal/domain"
)

// MockArticleAuthorService is a mock of ArticleAuthorService interface.
type MockArticleAuthorService struct {
	ctrl     *gomock.Controller
	recorder *MockArticleAuthorServiceMockRecorder
	isgomock struct{}
}

// MockArticleAuthorServiceMockRecorder is the mock recorder for MockArticleAuthorService.
type MockArticleAuthorServiceMockRecorder struct {
	mock *MockArticleAuthorService
}

// NewMockArticleAuthorService creates a new mock instance.
func NewMockArticleAuthorService(ctrl *gomock.Controller) *MockArticleAuthorService {
	mock := &MockArticleAuthorService{ctrl: ctrl}
	mock.recorder = &MockArticleAuthorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleAuthorService) EXPECT() *MockArticleAuthorServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockArticleAuthorService) Delete(ctx context.Context, id, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArticleAuthorServiceMockRecorder) Delete(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticleAuthorService)(nil).Delete), ctx, id, uid)
}

// Detail mocks base method.
func (m *MockArticleAuthorService) Detail(ctx context.Context, id, uid int64) (domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id, uid)
	ret0, _ := ret[0].(domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockArticleAuthorServiceMockRecorder) Detail(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockArticleAuthorService)(nil).Detail), ctx, id, uid)
}

// Edit mocks base method.
func (m *MockArticleAuthorService) Edit(ctx context.Context, article domain.Article) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", ctx, article)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit indicates an expected call of Edit.
func (mr *MockArticleAuthorServiceMockRecorder) Edit(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockArticleAuthorService)(nil).Edit), ctx, article)
}

// List mocks base method.
func (m *MockArticleAuthorService) List(ctx context.Context, uid int64) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, uid)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockArticleAuthorServiceMockRecorder) List(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockArticleAuthorService)(nil).List), ctx, uid)
}

// Page mocks base method.
func (m *MockArticleAuthorService) Page(ctx context.Context, uid int64, page, pageSize int) ([]domain.Article, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Page", ctx, uid, page, pageSize)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Page indicates an expected call of Page.
func (mr *MockArticleAuthorServiceMockRecorder) Page(ctx, uid, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Page", reflect.TypeOf((*MockArticleAuthorService)(nil).Page), ctx, uid, page, pageSize)
}

// Publish mocks base method.
func (m *MockArticleAuthorService) Publish(ctx context.Context, article domain.Article) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, article)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockArticleAuthorServiceMockRecorder) Publish(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockArticleAuthorService)(nil).Publish), ctx, article)
}

// Withdraw mocks base method.
func (m *MockArticleAuthorService) Withdraw(ctx context.Context, id, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, id, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockArticleAuthorServiceMockRecorder) Withdraw(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockArticleAuthorService)(nil).Withdraw), ctx, id, uid)
}

// MockArticleReaderService is a mock of ArticleReaderService interface.
type MockArticleReaderService struct {
	ctrl     *gomock.Controller
	recorder *MockArticleReaderServiceMockRecorder
	isgomock struct{}
}

// MockArticleReaderServiceMockRecorder is the mock recorder for MockArticleReaderService.
type MockArticleReaderServiceMockRecorder struct {
	mock *MockArticleReaderService
}

// NewMockArticleReaderService creates a new mock instance.
func NewMockArticleReaderService(ctrl *gomock.Controller) *MockArticleReaderService {
	mock := &MockArticleReaderService{ctrl: ctrl}
	mock.recorder = &MockArticleReaderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleReaderService) EXPECT() *MockArticleReaderServiceMockRecorder {
	return m.recorder
}

// AuthorArticles mocks base method.
func (m *MockArticleReaderService) AuthorArticles(ctx context.Context, uid int64, page, pageSize int) ([]domain.ArticleWithStats, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorArticles", ctx, uid, page, pageSize)
	ret0, _ := ret[0].([]domain.ArticleWithStats)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// AuthorArticles indicates an expected call of AuthorArticles.
func (mr *MockArticleReaderServiceMockRecorder) AuthorArticles(ctx, uid, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorArticles", reflect.TypeOf((*MockArticleReaderService)(nil).AuthorArticles), ctx, uid, page, pageSize)
}

// BatchDetail mocks base method.
func (m *MockArticleReaderService) BatchDetail(ctx context.Context, ids []int64) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDetail", ctx, ids)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDetail indicates an expected call of BatchDetail.
func (mr *MockArticleReaderServiceMockRecorder) BatchDetail(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDetail", reflect.TypeOf((*MockArticleReaderService)(nil).BatchDetail), ctx, ids)
}

// CountByIds mocks base method.
func (m *MockArticleReaderService) CountByIds(ctx context.Context, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByIds", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByIds indicates an expected call of CountByIds.
func (mr *MockArticleReaderServiceMockRecorder) CountByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByIds", reflect.TypeOf((*MockArticleReaderService)(nil).CountByIds), ctx, ids)
}

// Detail mocks base method.
func (m *MockArticleReaderService) Detail(ctx context.Context, id int64) (domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockArticleReaderServiceMockRecorder) Detail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockArticleReaderService)(nil).Detail), ctx, id)
}

// ListAuthorBriefs mocks base method.
func (m *MockArticleReaderService) ListAuthorBriefs(ctx context.Context, authorId int64, limit int) ([]domain.ArticleBrief, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuthorBriefs", ctx, authorId, limit)
	ret0, _ := ret[0].([]domain.ArticleBrief)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuthorBriefs indicates an expected call of ListAuthorBriefs.
func (mr *MockArticleReaderServiceMockRecorder) ListAuthorBriefs(ctx, authorId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthorBriefs", reflect.TypeOf((*MockArticleReaderService)(nil).ListAuthorBriefs), ctx, authorId, limit)
}

// Page mocks base method.
func (m *MockArticleReaderService) Page(ctx context.Context, page, pageSize int) ([]domain.Article, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Page", ctx, page, pageSize)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Page indicates an expected call of Page.
func (mr *MockArticleReaderServiceMockRecorder) Page(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Page", reflect.TypeOf((*MockArticleReaderService)(nil).Page), ctx, page, pageSize)
}
