// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/chat_tools.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/chat_tools.go -package=svcmocks -destination=./internal/service/mocks/chat_tools_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
	ai "github.com/webook/internal/service/ai"
)

// MockToolExecutor is a mock of ToolExecutor interface.
type MockToolExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockToolExecutorMockRecorder
	isgomock struct{}
}

// MockToolExecutorMockRecorder is the mock recorder for MockToolExecutor.
type MockToolExecutorMockRecorder struct {
	mock *MockToolExecutor
}

// NewMockToolExecutor creates a new mock instance.
func NewMockToolExecutor(ctrl *gomock.Controller) *MockToolExecutor {
	mock := &MockToolExecutor{ctrl: ctrl}
	mock.recorder = &MockToolExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolExecutor) EXPECT() *MockToolExecutorMockRecorder {
	return m.recorder
}

// Definitions mocks base method.
func (m *MockToolExecutor) Definitions() []ai.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Definitions")
	ret0, _ := ret[0].([]ai.Tool)
	return ret0
}

// Definitions indicates an expected call of Definitions.
func (mr *MockToolExecutorMockRecorder) Definitions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Definitions", reflect.TypeOf((*MockToolExecutor)(nil).Definitions))
}

// Execute mocks base method.
func (m *MockToolExecutor) Execute(ctx context.Context, uid int64, name string, args map[string]any) (domain.ToolResultData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, uid, name, args)
	ret0, _ := ret[0].(domain.ToolResultData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockToolExecutorMockRecorder) Execute(ctx, uid, name, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockToolExecutor)(nil).Execute), ctx, uid, name, args)
}
