// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/click_event.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/click_event.go -package=svcmocks -destination=./internal/service/mocks/click_event_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	domain "gitee.com/train-cloud/geektime-basic-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClickEventService is a mock of ClickEventService interface.
type MockClickEventService struct {
	ctrl     *gomock.Controller
	recorder *MockClickEventServiceMockRecorder
	isgomock struct{}
}

// MockClickEventServiceMockRecorder is the mock recorder for MockClickEventService.
type MockClickEventServiceMockRecorder struct {
	mock *MockClickEventService
}

// NewMockClickEventService creates a new mock instance.
func NewMockClickEventService(ctrl *gomock.Controller) *MockClickEventService {
	mock := &MockClickEventService{ctrl: ctrl}
	mock.recorder = &MockClickEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickEventService) EXPECT() *MockClickEventServiceMockRecorder {
	return m.recorder
}

// Dashboard mocks base method.
func (m *MockClickEventService) Dashboard(ctx context.Context) (domain.ClickEventDashboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dashboard", ctx)
	ret0, _ := ret[0].(domain.ClickEventDashboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dashboard indicates an expected call of Dashboard.
func (mr *MockClickEventServiceMockRecorder) Dashboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dashboard", reflect.TypeOf((*MockClickEventService)(nil).Dashboard), ctx)
}

// RecordClick mocks base method.
func (m *MockClickEventService) RecordClick(ctx context.Context, uid, articleId, convId int64, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClick", ctx, uid, articleId, convId, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClick indicates an expected call of RecordClick.
func (mr *MockClickEventServiceMockRecorder) RecordClick(ctx, uid, articleId, convId, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClick", reflect.TypeOf((*MockClickEventService)(nil).RecordClick), ctx, uid, articleId, convId, source)
}
