// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/comment.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/comment.go -package=svcmocks -destination=./internal/service/mocks/comment_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/webook/internal/domain"
)

// MockCommentService is a mock of CommentService interface.
type MockCommentService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceMockRecorder
	isgomock struct{}
}

// MockCommentServiceMockRecorder is the mock recorder for MockCommentService.
type MockCommentServiceMockRecorder struct {
	mock *MockCommentService
}

// NewMockCommentService creates a new mock instance.
func NewMockCommentService(ctrl *gomock.Controller) *MockCommentService {
	mock := &MockCommentService{ctrl: ctrl}
	mock.recorder = &MockCommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentService) EXPECT() *MockCommentServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentService) Create(ctx context.Context, uid, articleId int64, content string, pid int64) (domain.CommentView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, uid, articleId, content, pid)
	ret0, _ := ret[0].(domain.CommentView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommentServiceMockRecorder) Create(ctx, uid, articleId, content, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentService)(nil).Create), ctx, uid, articleId, content, pid)
}

// Delete mocks base method.
func (m *MockCommentService) Delete(ctx context.Context, id, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentServiceMockRecorder) Delete(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentService)(nil).Delete), ctx, id, uid)
}

// List mocks base method.
func (m *MockCommentService) List(ctx context.Context, uid, articleId int64, sort string, offset, limit int32) ([]domain.CommentView, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, uid, articleId, sort, offset, limit)
	ret0, _ := ret[0].([]domain.CommentView)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCommentServiceMockRecorder) List(ctx, uid, articleId, sort, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommentService)(nil).List), ctx, uid, articleId, sort, offset, limit)
}

// Replies mocks base method.
func (m *MockCommentService) Replies(ctx context.Context, uid, rootId int64, offset, limit int32) ([]domain.CommentView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replies", ctx, uid, rootId, offset, limit)
	ret0, _ := ret[0].([]domain.CommentView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replies indicates an expected call of Replies.
func (mr *MockCommentServiceMockRecorder) Replies(ctx, uid, rootId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replies", reflect.TypeOf((*MockCommentService)(nil).Replies), ctx, uid, rootId, offset, limit)
}
