// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/interaction.go
//
// Generated by this command:
//
//	mockgen -source=./service/interaction.go -package=svcmocks -destination=./service/mocks/interaction_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/internal/domain"
)

// MockInteractionService is a mock of InteractionService interface.
type MockInteractionService struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionServiceMockRecorder
	isgomock struct{}
}

// MockInteractionServiceMockRecorder is the mock recorder for MockInteractionService.
type MockInteractionServiceMockRecorder struct {
	mock *MockInteractionService
}

// NewMockInteractionService creates a new mock instance.
func NewMockInteractionService(ctrl *gomock.Controller) *MockInteractionService {
	mock := &MockInteractionService{ctrl: ctrl}
	mock.recorder = &MockInteractionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractionService) EXPECT() *MockInteractionServiceMockRecorder {
	return m.recorder
}

// CancelCollect mocks base method.
func (m *MockInteractionService) CancelCollect(ctx context.Context, uid int64, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelCollect", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelCollect indicates an expected call of CancelCollect.
func (mr *MockInteractionServiceMockRecorder) CancelCollect(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelCollect", reflect.TypeOf((*MockInteractionService)(nil).CancelCollect), ctx, uid, biz, bizId)
}

// CancelLike mocks base method.
func (m *MockInteractionService) CancelLike(ctx context.Context, uid int64, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelLike", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelLike indicates an expected call of CancelLike.
func (mr *MockInteractionServiceMockRecorder) CancelLike(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelLike", reflect.TypeOf((*MockInteractionService)(nil).CancelLike), ctx, uid, biz, bizId)
}

// Collect mocks base method.
func (m *MockInteractionService) Collect(ctx context.Context, uid int64, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Collect indicates an expected call of Collect.
func (mr *MockInteractionServiceMockRecorder) Collect(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockInteractionService)(nil).Collect), ctx, uid, biz, bizId)
}

// FindByBizIds mocks base method.
func (m *MockInteractionService) FindByBizIds(ctx context.Context, biz string, bizIds []int64) (map[int64]domain.Interaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBizIds", ctx, biz, bizIds)
	ret0, _ := ret[0].(map[int64]domain.Interaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBizIds indicates an expected call of FindByBizIds.
func (mr *MockInteractionServiceMockRecorder) FindByBizIds(ctx, biz, bizIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBizIds", reflect.TypeOf((*MockInteractionService)(nil).FindByBizIds), ctx, biz, bizIds)
}

// FindInteraction mocks base method.
func (m *MockInteractionService) FindInteraction(ctx context.Context, uid int64, biz string, bizId int64) (domain.Interaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInteraction", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(domain.Interaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInteraction indicates an expected call of FindInteraction.
func (mr *MockInteractionServiceMockRecorder) FindInteraction(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInteraction", reflect.TypeOf((*MockInteractionService)(nil).FindInteraction), ctx, uid, biz, bizId)
}

// FindUserLiked mocks base method.
func (m *MockInteractionService) FindUserLiked(ctx context.Context, uid int64, biz string, bizIds []int64) (map[int64]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserLiked", ctx, uid, biz, bizIds)
	ret0, _ := ret[0].(map[int64]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserLiked indicates an expected call of FindUserLiked.
func (mr *MockInteractionServiceMockRecorder) FindUserLiked(ctx, uid, biz, bizIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserLiked", reflect.TypeOf((*MockInteractionService)(nil).FindUserLiked), ctx, uid, biz, bizIds)
}

// FindUserState mocks base method.
func (m *MockInteractionService) FindUserState(ctx context.Context, uid int64, biz string, bizId int64) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserState", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindUserState indicates an expected call of FindUserState.
func (mr *MockInteractionServiceMockRecorder) FindUserState(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserState", reflect.TypeOf((*MockInteractionService)(nil).FindUserState), ctx, uid, biz, bizId)
}

// IncrReadCount mocks base method.
func (m *MockInteractionService) IncrReadCount(ctx context.Context, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrReadCount", ctx, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrReadCount indicates an expected call of IncrReadCount.
func (mr *MockInteractionServiceMockRecorder) IncrReadCount(ctx, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrReadCount", reflect.TypeOf((*MockInteractionService)(nil).IncrReadCount), ctx, biz, bizId)
}

// Like mocks base method.
func (m *MockInteractionService) Like(ctx context.Context, uid int64, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockInteractionServiceMockRecorder) Like(ctx, uid, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockInteractionService)(nil).Like), ctx, uid, biz, bizId)
}

// ListCollectedBizIds mocks base method.
func (m *MockInteractionService) ListCollectedBizIds(ctx context.Context, uid int64, biz string, limit int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectedBizIds", ctx, uid, biz, limit)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollectedBizIds indicates an expected call of ListCollectedBizIds.
func (mr *MockInteractionServiceMockRecorder) ListCollectedBizIds(ctx, uid, biz, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectedBizIds", reflect.TypeOf((*MockInteractionService)(nil).ListCollectedBizIds), ctx, uid, biz, limit)
}

// ListHotBizIds mocks base method.
func (m *MockInteractionService) ListHotBizIds(ctx context.Context, biz string, limit int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHotBizIds", ctx, biz, limit)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHotBizIds indicates an expected call of ListHotBizIds.
func (mr *MockInteractionServiceMockRecorder) ListHotBizIds(ctx, biz, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHotBizIds", reflect.TypeOf((*MockInteractionService)(nil).ListHotBizIds), ctx, biz, limit)
}
