// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/ranking.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/ranking.go -package=svcmocks -destination=./internal/service/mocks/ranking_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/internal/domain"
)

// MockRankingService is a mock of RankingService interface.
type MockRankingService struct {
	ctrl     *gomock.Controller
	recorder *MockRankingServiceMockRecorder
	isgomock struct{}
}

// MockRankingServiceMockRecorder is the mock recorder for MockRankingService.
type MockRankingServiceMockRecorder struct {
	mock *MockRankingService
}

// NewMockRankingService creates a new mock instance.
func NewMockRankingService(ctrl *gomock.Controller) *MockRankingService {
	mock := &MockRankingService{ctrl: ctrl}
	mock.recorder = &MockRankingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingService) EXPECT() *MockRankingServiceMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockRankingService) Archive(ctx context.Context, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockRankingServiceMockRecorder) Archive(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockRankingService)(nil).Archive), ctx, date)
}

// ListArchiveDates mocks base method.
func (m *MockRankingService) ListArchiveDates(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArchiveDates", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArchiveDates indicates an expected call of ListArchiveDates.
func (mr *MockRankingServiceMockRecorder) ListArchiveDates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArchiveDates", reflect.TypeOf((*MockRankingService)(nil).ListArchiveDates), ctx)
}

// OnClick mocks base method.
func (m *MockRankingService) OnClick(ctx context.Context, uid, articleId int64, rank int, dim string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnClick", ctx, uid, articleId, rank, dim)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnClick indicates an expected call of OnClick.
func (mr *MockRankingServiceMockRecorder) OnClick(ctx, uid, articleId, rank, dim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnClick", reflect.TypeOf((*MockRankingService)(nil).OnClick), ctx, uid, articleId, rank, dim)
}

// Page mocks base method.
func (m *MockRankingService) Page(ctx context.Context, date, dim, cat string, page, pageSize int) ([]domain.ArticleRanking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Page", ctx, date, dim, cat, page, pageSize)
	ret0, _ := ret[0].([]domain.ArticleRanking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Page indicates an expected call of Page.
func (mr *MockRankingServiceMockRecorder) Page(ctx, date, dim, cat, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Page", reflect.TypeOf((*MockRankingService)(nil).Page), ctx, date, dim, cat, page, pageSize)
}

// RecomputeBest mocks base method.
func (m *MockRankingService) RecomputeBest(ctx context.Context, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecomputeBest", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecomputeBest indicates an expected call of RecomputeBest.
func (mr *MockRankingServiceMockRecorder) RecomputeBest(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecomputeBest", reflect.TypeOf((*MockRankingService)(nil).RecomputeBest), ctx, date)
}

// RecomputeHot mocks base method.
func (m *MockRankingService) RecomputeHot(ctx context.Context, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecomputeHot", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecomputeHot indicates an expected call of RecomputeHot.
func (mr *MockRankingServiceMockRecorder) RecomputeHot(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecomputeHot", reflect.TypeOf((*MockRankingService)(nil).RecomputeHot), ctx, date)
}

// RecomputeNew mocks base method.
func (m *MockRankingService) RecomputeNew(ctx context.Context, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecomputeNew", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecomputeNew indicates an expected call of RecomputeNew.
func (mr *MockRankingServiceMockRecorder) RecomputeNew(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecomputeNew", reflect.TypeOf((*MockRankingService)(nil).RecomputeNew), ctx, date)
}
