// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/relation.go
//
// Generated by this command:
//
//	mockgen -source=./service/relation.go -package=svcmocks -destination=./service/mocks/relation_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/internal/domain"
)

// MockRelationService is a mock of RelationService interface.
type MockRelationService struct {
	ctrl     *gomock.Controller
	recorder *MockRelationServiceMockRecorder
	isgomock struct{}
}

// MockRelationServiceMockRecorder is the mock recorder for MockRelationService.
type MockRelationServiceMockRecorder struct {
	mock *MockRelationService
}

// NewMockRelationService creates a new mock instance.
func NewMockRelationService(ctrl *gomock.Controller) *MockRelationService {
	mock := &MockRelationService{ctrl: ctrl}
	mock.recorder = &MockRelationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationService) EXPECT() *MockRelationServiceMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockRelationService) Block(ctx context.Context, uid, targetId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", ctx, uid, targetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Block indicates an expected call of Block.
func (mr *MockRelationServiceMockRecorder) Block(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockRelationService)(nil).Block), ctx, uid, targetId)
}

// Blocklist mocks base method.
func (m *MockRelationService) Blocklist(ctx context.Context, uid, cursor int64, limit int32) ([]domain.RelationUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocklist", ctx, uid, cursor, limit)
	ret0, _ := ret[0].([]domain.RelationUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Blocklist indicates an expected call of Blocklist.
func (mr *MockRelationServiceMockRecorder) Blocklist(ctx, uid, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocklist", reflect.TypeOf((*MockRelationService)(nil).Blocklist), ctx, uid, cursor, limit)
}

// Follow mocks base method.
func (m *MockRelationService) Follow(ctx context.Context, followerId, followeeId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, followerId, followeeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockRelationServiceMockRecorder) Follow(ctx, followerId, followeeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockRelationService)(nil).Follow), ctx, followerId, followeeId)
}

// Followees mocks base method.
func (m *MockRelationService) Followees(ctx context.Context, userId, cursor int64, limit int32) ([]domain.RelationUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Followees", ctx, userId, cursor, limit)
	ret0, _ := ret[0].([]domain.RelationUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Followees indicates an expected call of Followees.
func (mr *MockRelationServiceMockRecorder) Followees(ctx, userId, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Followees", reflect.TypeOf((*MockRelationService)(nil).Followees), ctx, userId, cursor, limit)
}

// Followers mocks base method.
func (m *MockRelationService) Followers(ctx context.Context, userId, cursor int64, limit int32) ([]domain.RelationUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Followers", ctx, userId, cursor, limit)
	ret0, _ := ret[0].([]domain.RelationUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Followers indicates an expected call of Followers.
func (mr *MockRelationServiceMockRecorder) Followers(ctx, userId, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Followers", reflect.TypeOf((*MockRelationService)(nil).Followers), ctx, userId, cursor, limit)
}

// Stat mocks base method.
func (m *MockRelationService) Stat(ctx context.Context, viewerId, userId int64) (domain.RelationStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", ctx, viewerId, userId)
	ret0, _ := ret[0].(domain.RelationStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockRelationServiceMockRecorder) Stat(ctx, viewerId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockRelationService)(nil).Stat), ctx, viewerId, userId)
}

// Unblock mocks base method.
func (m *MockRelationService) Unblock(ctx context.Context, uid, targetId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unblock", ctx, uid, targetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unblock indicates an expected call of Unblock.
func (mr *MockRelationServiceMockRecorder) Unblock(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unblock", reflect.TypeOf((*MockRelationService)(nil).Unblock), ctx, uid, targetId)
}

// Unfollow mocks base method.
func (m *MockRelationService) Unfollow(ctx context.Context, followerId, followeeId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, followerId, followeeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockRelationServiceMockRecorder) Unfollow(ctx, followerId, followeeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockRelationService)(nil).Unfollow), ctx, followerId, followeeId)
}
