// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/tag.go
//
// Generated by this command:
//
//	mockgen -source=./service/tag.go -package=svcmocks -destination=./service/mocks/tag_mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/internal/domain"
)

// MockTagService is a mock of TagService interface.
type MockTagService struct {
	ctrl     *gomock.Controller
	recorder *MockTagServiceMockRecorder
	isgomock struct{}
}

// MockTagServiceMockRecorder is the mock recorder for MockTagService.
type MockTagServiceMockRecorder struct {
	mock *MockTagService
}

// NewMockTagService creates a new mock instance.
func NewMockTagService(ctrl *gomock.Controller) *MockTagService {
	mock := &MockTagService{ctrl: ctrl}
	mock.recorder = &MockTagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagService) EXPECT() *MockTagServiceMockRecorder {
	return m.recorder
}

// ClearTags mocks base method.
func (m *MockTagService) ClearTags(ctx context.Context, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTags", ctx, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTags indicates an expected call of ClearTags.
func (mr *MockTagServiceMockRecorder) ClearTags(ctx, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTags", reflect.TypeOf((*MockTagService)(nil).ClearTags), ctx, biz, bizId)
}

// Detail mocks base method.
func (m *MockTagService) Detail(ctx context.Context, slug string, viewerId int64) (domain.Tag, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, slug, viewerId)
	ret0, _ := ret[0].(domain.Tag)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Detail indicates an expected call of Detail.
func (mr *MockTagServiceMockRecorder) Detail(ctx, slug, viewerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockTagService)(nil).Detail), ctx, slug, viewerId)
}

// Follow mocks base method.
func (m *MockTagService) Follow(ctx context.Context, uid int64, slug string) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, uid, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Follow indicates an expected call of Follow.
func (mr *MockTagServiceMockRecorder) Follow(ctx, uid, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockTagService)(nil).Follow), ctx, uid, slug)
}

// Recommend mocks base method.
func (m *MockTagService) Recommend(ctx context.Context, title, content string) ([]domain.TagCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recommend", ctx, title, content)
	ret0, _ := ret[0].([]domain.TagCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recommend indicates an expected call of Recommend.
func (mr *MockTagServiceMockRecorder) Recommend(ctx, title, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recommend", reflect.TypeOf((*MockTagService)(nil).Recommend), ctx, title, content)
}

// Suggest mocks base method.
func (m *MockTagService) Suggest(ctx context.Context, prefix string, limit int) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suggest", ctx, prefix, limit)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Suggest indicates an expected call of Suggest.
func (mr *MockTagServiceMockRecorder) Suggest(ctx, prefix, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suggest", reflect.TypeOf((*MockTagService)(nil).Suggest), ctx, prefix, limit)
}

// SyncTags mocks base method.
func (m *MockTagService) SyncTags(ctx context.Context, biz string, bizId int64, names []string, source string) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncTags", ctx, biz, bizId, names, source)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncTags indicates an expected call of SyncTags.
func (mr *MockTagServiceMockRecorder) SyncTags(ctx, biz, bizId, names, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncTags", reflect.TypeOf((*MockTagService)(nil).SyncTags), ctx, biz, bizId, names, source)
}

// TagArticles mocks base method.
func (m *MockTagService) TagArticles(ctx context.Context, slug, sortBy string, page, size int) (domain.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagArticles", ctx, slug, sortBy, page, size)
	ret0, _ := ret[0].(domain.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagArticles indicates an expected call of TagArticles.
func (mr *MockTagServiceMockRecorder) TagArticles(ctx, slug, sortBy, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagArticles", reflect.TypeOf((*MockTagService)(nil).TagArticles), ctx, slug, sortBy, page, size)
}

// TagsByBiz mocks base method.
func (m *MockTagService) TagsByBiz(ctx context.Context, biz string, bizIds []int64) (map[int64][]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagsByBiz", ctx, biz, bizIds)
	ret0, _ := ret[0].(map[int64][]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagsByBiz indicates an expected call of TagsByBiz.
func (mr *MockTagServiceMockRecorder) TagsByBiz(ctx, biz, bizIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagsByBiz", reflect.TypeOf((*MockTagService)(nil).TagsByBiz), ctx, biz, bizIds)
}

// Unfollow mocks base method.
func (m *MockTagService) Unfollow(ctx context.Context, uid int64, slug string) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, uid, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockTagServiceMockRecorder) Unfollow(ctx, uid, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockTagService)(nil).Unfollow), ctx, uid, slug)
}
