// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/boyxs/train-go/webook/pkg/grpcx"
	"github.com/boyxs/train-go/webook/relation/grpc"
	"github.com/boyxs/train-go/webook/relation/ioc"
	"github.com/boyxs/train-go/webook/relation/repository"
	"github.com/boyxs/train-go/webook/relation/repository/cache"
	"github.com/boyxs/train-go/webook/relation/repository/dao"
	"github.com/boyxs/train-go/webook/relation/service"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	timezoneReady := ioc.InitTimezone()
	loggerX := ioc.InitLogger()
	db := ioc.InitDB(timezoneReady, loggerX)
	relationDAO := dao.NewGormRelationDAO(db)
	cmdable := ioc.InitRedis()
	relationCache := cache.NewRedisRelationCache(cmdable)
	relationRepository := repository.NewCacheRelationRepository(relationDAO, relationCache, loggerX)
	relationService := service.NewInternalRelationService(relationRepository)
	relationServer := grpc.NewRelationServer(relationService)
	client, cleanup, err := ioc.InitEtcdClient()
	if err != nil {
		return App{}, nil, err
	}
	tracerProvider, cleanup2, err := ioc.InitOTel()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	server := ioc.InitGRPCServer(relationServer, client, loggerX, tracerProvider)
	app := App{
		GRPCServer: server,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App relation 服务进程入口（纯 gRPC server）。
type App struct {
	GRPCServer *grpcx.Server
}
