// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/boyxs/train-go/webook/api/gen/article/v1 (interfaces: ArticleReaderServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./service/grpcmocks/article.mock.go -package=grpcmocks github.com/boyxs/train-go/webook/api/gen/article/v1 ArticleReaderServiceClient
//

// Package grpcmocks is a generated GoMock package.
package grpcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	articlev1 "github.com/boyxs/train-go/webook/api/gen/article/v1"
)

// MockArticleReaderServiceClient is a mock of ArticleReaderServiceClient interface.
type MockArticleReaderServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockArticleReaderServiceClientMockRecorder
	isgomock struct{}
}

// MockArticleReaderServiceClientMockRecorder is the mock recorder for MockArticleReaderServiceClient.
type MockArticleReaderServiceClientMockRecorder struct {
	mock *MockArticleReaderServiceClient
}

// NewMockArticleReaderServiceClient creates a new mock instance.
func NewMockArticleReaderServiceClient(ctrl *gomock.Controller) *MockArticleReaderServiceClient {
	mock := &MockArticleReaderServiceClient{ctrl: ctrl}
	mock.recorder = &MockArticleReaderServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleReaderServiceClient) EXPECT() *MockArticleReaderServiceClientMockRecorder {
	return m.recorder
}

// BatchGetArticles mocks base method.
func (m *MockArticleReaderServiceClient) BatchGetArticles(ctx context.Context, in *articlev1.BatchGetArticlesRequest, opts ...grpc.CallOption) (*articlev1.BatchGetArticlesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetArticles", varargs...)
	ret0, _ := ret[0].(*articlev1.BatchGetArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetArticles indicates an expected call of BatchGetArticles.
func (mr *MockArticleReaderServiceClientMockRecorder) BatchGetArticles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetArticles", reflect.TypeOf((*MockArticleReaderServiceClient)(nil).BatchGetArticles), varargs...)
}

// GetArticle mocks base method.
func (m *MockArticleReaderServiceClient) GetArticle(ctx context.Context, in *articlev1.GetArticleRequest, opts ...grpc.CallOption) (*articlev1.Article, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArticle", varargs...)
	ret0, _ := ret[0].(*articlev1.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockArticleReaderServiceClientMockRecorder) GetArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockArticleReaderServiceClient)(nil).GetArticle), varargs...)
}

// ListAuthorArticles mocks base method.
func (m *MockArticleReaderServiceClient) ListAuthorArticles(ctx context.Context, in *articlev1.ListAuthorArticlesRequest, opts ...grpc.CallOption) (*articlev1.ListAuthorArticlesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAuthorArticles", varargs...)
	ret0, _ := ret[0].(*articlev1.ListAuthorArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuthorArticles indicates an expected call of ListAuthorArticles.
func (mr *MockArticleReaderServiceClientMockRecorder) ListAuthorArticles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthorArticles", reflect.TypeOf((*MockArticleReaderServiceClient)(nil).ListAuthorArticles), varargs...)
}
