// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/boyxs/train-go/webook/api/gen/relation/v1 (interfaces: RelationServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./service/grpcmocks/relation.mock.go -package=grpcmocks github.com/boyxs/train-go/webook/api/gen/relation/v1 RelationServiceClient
//

// Package grpcmocks is a generated GoMock package.
package grpcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	relationv1 "github.com/boyxs/train-go/webook/api/gen/relation/v1"
)

// MockRelationServiceClient is a mock of RelationServiceClient interface.
type MockRelationServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockRelationServiceClientMockRecorder
	isgomock struct{}
}

// MockRelationServiceClientMockRecorder is the mock recorder for MockRelationServiceClient.
type MockRelationServiceClientMockRecorder struct {
	mock *MockRelationServiceClient
}

// NewMockRelationServiceClient creates a new mock instance.
func NewMockRelationServiceClient(ctrl *gomock.Controller) *MockRelationServiceClient {
	mock := &MockRelationServiceClient{ctrl: ctrl}
	mock.recorder = &MockRelationServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationServiceClient) EXPECT() *MockRelationServiceClientMockRecorder {
	return m.recorder
}

// BatchGetStats mocks base method.
func (m *MockRelationServiceClient) BatchGetStats(ctx context.Context, in *relationv1.BatchGetStatsRequest, opts ...grpc.CallOption) (*relationv1.BatchGetStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetStats", varargs...)
	ret0, _ := ret[0].(*relationv1.BatchGetStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetStats indicates an expected call of BatchGetStats.
func (mr *MockRelationServiceClientMockRecorder) BatchGetStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetStats", reflect.TypeOf((*MockRelationServiceClient)(nil).BatchGetStats), varargs...)
}

// Block mocks base method.
func (m *MockRelationServiceClient) Block(ctx context.Context, in *relationv1.BlockRequest, opts ...grpc.CallOption) (*relationv1.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Block", varargs...)
	ret0, _ := ret[0].(*relationv1.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Block indicates an expected call of Block.
func (mr *MockRelationServiceClientMockRecorder) Block(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockRelationServiceClient)(nil).Block), varargs...)
}

// Follow mocks base method.
func (m *MockRelationServiceClient) Follow(ctx context.Context, in *relationv1.FollowRequest, opts ...grpc.CallOption) (*relationv1.FollowResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Follow", varargs...)
	ret0, _ := ret[0].(*relationv1.FollowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Follow indicates an expected call of Follow.
func (mr *MockRelationServiceClientMockRecorder) Follow(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockRelationServiceClient)(nil).Follow), varargs...)
}

// GetRelation mocks base method.
func (m *MockRelationServiceClient) GetRelation(ctx context.Context, in *relationv1.GetRelationRequest, opts ...grpc.CallOption) (*relationv1.GetRelationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRelation", varargs...)
	ret0, _ := ret[0].(*relationv1.GetRelationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelation indicates an expected call of GetRelation.
func (mr *MockRelationServiceClientMockRecorder) GetRelation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelation", reflect.TypeOf((*MockRelationServiceClient)(nil).GetRelation), varargs...)
}

// GetStats mocks base method.
func (m *MockRelationServiceClient) GetStats(ctx context.Context, in *relationv1.GetStatsRequest, opts ...grpc.CallOption) (*relationv1.GetStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStats", varargs...)
	ret0, _ := ret[0].(*relationv1.GetStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRelationServiceClientMockRecorder) GetStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRelationServiceClient)(nil).GetStats), varargs...)
}

// ListBlocks mocks base method.
func (m *MockRelationServiceClient) ListBlocks(ctx context.Context, in *relationv1.ListRequest, opts ...grpc.CallOption) (*relationv1.ListBlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBlocks", varargs...)
	ret0, _ := ret[0].(*relationv1.ListBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlocks indicates an expected call of ListBlocks.
func (mr *MockRelationServiceClientMockRecorder) ListBlocks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlocks", reflect.TypeOf((*MockRelationServiceClient)(nil).ListBlocks), varargs...)
}

// ListFollowees mocks base method.
func (m *MockRelationServiceClient) ListFollowees(ctx context.Context, in *relationv1.ListRequest, opts ...grpc.CallOption) (*relationv1.ListFollowResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFollowees", varargs...)
	ret0, _ := ret[0].(*relationv1.ListFollowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowees indicates an expected call of ListFollowees.
func (mr *MockRelationServiceClientMockRecorder) ListFollowees(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowees", reflect.TypeOf((*MockRelationServiceClient)(nil).ListFollowees), varargs...)
}

// ListFollowers mocks base method.
func (m *MockRelationServiceClient) ListFollowers(ctx context.Context, in *relationv1.ListRequest, opts ...grpc.CallOption) (*relationv1.ListFollowResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFollowers", varargs...)
	ret0, _ := ret[0].(*relationv1.ListFollowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowers indicates an expected call of ListFollowers.
func (mr *MockRelationServiceClientMockRecorder) ListFollowers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowers", reflect.TypeOf((*MockRelationServiceClient)(nil).ListFollowers), varargs...)
}

// Unblock mocks base method.
func (m *MockRelationServiceClient) Unblock(ctx context.Context, in *relationv1.BlockRequest, opts ...grpc.CallOption) (*relationv1.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Unblock", varargs...)
	ret0, _ := ret[0].(*relationv1.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unblock indicates an expected call of Unblock.
func (mr *MockRelationServiceClientMockRecorder) Unblock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unblock", reflect.TypeOf((*MockRelationServiceClient)(nil).Unblock), varargs...)
}

// Unfollow mocks base method.
func (m *MockRelationServiceClient) Unfollow(ctx context.Context, in *relationv1.FollowRequest, opts ...grpc.CallOption) (*relationv1.FollowResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Unfollow", varargs...)
	ret0, _ := ret[0].(*relationv1.FollowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockRelationServiceClientMockRecorder) Unfollow(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockRelationServiceClient)(nil).Unfollow), varargs...)
}
