etcd:
    endpoint: http://127.0.0.1:2379
    path: /webook
    type: yaml

mysql:
    dsn: root:13520@tcp(localhost:3306)/webook?parseTime=true&loc=UTC

redis:
    addr: 127.0.0.1:6379
    password: "13520"

#web:
#  logger:
#    allowReqBody: true
#    allowResBody: true
#    maxReqLen: 2048
#    maxResLen: 2048
#    maxPathLen: 1024

#etcdctl --endpoints=127.0.0.1:2379 put /webook < config/dev.yaml

#dev.yaml 开发 (development)
#stg.yaml 预发布 (staging)
#prod.yaml 生产 (production)
