etcd:
  endpoint: "http://webook-etcd:2379"
  path: '/webook'
  type: 'yaml'

mysql:
  dsn: 'root:13520@tcp(webook-mysql:3306)/webook'

redis:
  addr: 'webook-redis:6379'
  password: '13520'

logger:
  level:
    l: 0
  development: false
  encoding: 'json'
  outputPaths: [ 'stdout' ]
  errorOutputPaths: [ 'stderr' ]

#web:
#  logger:
#    allowReqBody: true
#    allowResBody: true
#    maxReqLen: 2048
#    maxResLen: 2048
#    maxPathLen: 1024

#etcdctl put /webook < config/k8s.yaml
