etcd:
  endpoint: "http://webook-etcd:2379"
  path: '/webook'
  type: 'yaml'

mysql:
  dsn: 'root:13520@tcp(webook-mysql:3306)/webook?parseTime=true&loc=UTC'

redis:
  addr: 'webook-redis:6379'
  password: '13520'

logger:
  level:
    l: 0
  development: false
  encoding: 'json'
  outputPaths: [ 'stdout' ]
  errorOutputPaths: [ 'stderr' ]

#web:
#  logger:
#    allowReqBody: true
#    allowResBody: true
#    maxReqLen: 2048
#    maxResLen: 2048
#    maxPathLen: 1024

#etcdctl --endpoints=127.0.0.1:2379 /webook < config/k8s.yaml

#dev.yaml 开发 (development)
#stg.yaml 预发布 (staging)
#prd.yaml 生产 (production)
