// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/webook/internal/repository"
	"github.com/webook/internal/repository/cache"
	"github.com/webook/internal/repository/dao"
	"github.com/webook/internal/service"
	"github.com/webook/internal/web"
	"github.com/webook/internal/web/jwt"
	"github.com/webook/ioc"
	"github.com/webook/pkg/streamer"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

// 这个需要登录权限
func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	jwtHandler := jwt.NewRedisJwtHandler(cmdable)
	loggerX := InitLogger()
	v := ioc.InitMiddlewares(jwtHandler, loggerX, cmdable)
	db := InitDB()
	userDAO := dao.NewGormUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewRedisUserRepository(userDAO, userCache)
	userService := service.NewInternalUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewRedisCodeRepository(codeCache)
	smsService := ioc.InitSmsService(cmdable, loggerX)
	codeService := service.NewSmsCodeService(codeRepository, smsService)
	userHandler := web.NewInternalUserHandler(jwtHandler, userService, codeService, loggerX)
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleCache, loggerX)
	typedClient := ioc.InitESClient()
	articleSearchDAO := dao.NewElasticArticleDAO(typedClient)
	articleSearchRepository := repository.NewESArticleSearchRepository(articleSearchDAO)
	ollamaEmbeddingConfig := ioc.InitOllamaEmbeddingConfig()
	embeddingConfig := ioc.InitEmbeddingConfig()
	embeddingClient := ioc.InitEmbeddingClient(ollamaEmbeddingConfig, embeddingConfig, cmdable, loggerX)
	articleSearchService := service.NewArticleSearchService(articleSearchRepository, embeddingClient, loggerX)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository, articleSearchService, loggerX)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, loggerX)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	oAuth2Service := ioc.InitWechatOAuth2Service()
	oAuth2Handler := web.NewOAuth2WechatHandler(jwtHandler, oAuth2Service, userService)
	conversationDAO := dao.NewGormConversationDAO(db)
	conversationCache := cache.NewRedisConversationCache(cmdable)
	conversationRepository := repository.NewCacheConversationRepository(conversationDAO, conversationCache, loggerX)
	messageDAO := dao.NewGormMessageDAO(db)
	messageCache := cache.NewRedisMessageCache(cmdable)
	messageRepository := repository.NewCacheMessageRepository(messageDAO, messageCache, loggerX)
	llmConfig := ioc.InitLLMConfig()
	llmClient := ioc.InitLLMClient(llmConfig, loggerX)
	toolExecutor := service.NewAIChatToolExecutor(articleSearchService, articleReaderService, interactionRepository, loggerX)
	eventStreamer := streamer.NewRedisStreamer(cmdable)
	chatService := service.NewAIChatService(conversationRepository, messageRepository, llmClient, articleSearchService, toolExecutor, loggerX, eventStreamer)
	limiter := ioc.InitChatLimiter(cmdable)
	chatHandler := web.NewInternalChatHandler(chatService, loggerX, limiter)
	articleSearchHandler := web.NewInternalArticleSearchHandler(articleSearchService, loggerX)
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	clickEventCache := cache.NewRedisAIClickEventCache(cmdable)
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	clickEventHandler := web.NewAIClickEventHandler(clickEventService, loggerX)
	articlePolishService := service.NewAIArticlePolishService(llmClient)
	articlePolishHandler := web.NewAIArticlePolishHandler(articlePolishService, cmdable, loggerX)
	engine := ioc.InitWebServer(v, userHandler, articleAuthorHandler, articleReaderHandler, interactionHandler, oAuth2Handler, chatHandler, articleSearchHandler, clickEventHandler, articlePolishHandler)
	return engine
}

func InitArticleAuthorHandler() web.ArticleAuthorHandler {
	db := InitDB()
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	cmdable := InitRedis()
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	loggerX := InitLogger()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleCache, loggerX)
	typedClient := ioc.InitESClient()
	articleSearchDAO := dao.NewElasticArticleDAO(typedClient)
	articleSearchRepository := repository.NewESArticleSearchRepository(articleSearchDAO)
	ollamaEmbeddingConfig := ioc.InitOllamaEmbeddingConfig()
	embeddingConfig := ioc.InitEmbeddingConfig()
	embeddingClient := ioc.InitEmbeddingClient(ollamaEmbeddingConfig, embeddingConfig, cmdable, loggerX)
	articleSearchService := service.NewArticleSearchService(articleSearchRepository, embeddingClient, loggerX)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository, articleSearchService, loggerX)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	return articleAuthorHandler
}

func InitArticleReaderHandler() web.ArticleReaderHandler {
	db := InitDB()
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	cmdable := InitRedis()
	articleCache := cache.NewRedisArticleCache(cmdable)
	loggerX := InitLogger()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleCache, loggerX)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, loggerX)
	return articleReaderHandler
}

func InitInteractionHandler() web.InteractionHandler {
	db := InitDB()
	interactionDAO := dao.NewGormInteractionDAO(db)
	cmdable := InitRedis()
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	loggerX := InitLogger()
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	return interactionHandler
}

func InitArticlePolishHandler() web.ArticlePolishHandler {
	llmConfig := ioc.InitLLMConfig()
	loggerX := InitLogger()
	llmClient := ioc.InitLLMClient(llmConfig, loggerX)
	articlePolishService := service.NewAIArticlePolishService(llmClient)
	cmdable := InitRedis()
	articlePolishHandler := web.NewAIArticlePolishHandler(articlePolishService, cmdable, loggerX)
	return articlePolishHandler
}

func InitClickEventHandler() web.ClickEventHandler {
	db := InitDB()
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	cmdable := InitRedis()
	clickEventCache := cache.NewRedisAIClickEventCache(cmdable)
	loggerX := InitLogger()
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	clickEventHandler := web.NewAIClickEventHandler(clickEventService, loggerX)
	return clickEventHandler
}

func InitChatHandler() web.ChatHandler {
	db := InitDB()
	conversationDAO := dao.NewGormConversationDAO(db)
	cmdable := InitRedis()
	conversationCache := cache.NewRedisConversationCache(cmdable)
	loggerX := InitLogger()
	conversationRepository := repository.NewCacheConversationRepository(conversationDAO, conversationCache, loggerX)
	messageDAO := dao.NewGormMessageDAO(db)
	messageCache := cache.NewRedisMessageCache(cmdable)
	messageRepository := repository.NewCacheMessageRepository(messageDAO, messageCache, loggerX)
	llmConfig := ioc.InitLLMConfig()
	llmClient := ioc.InitLLMClient(llmConfig, loggerX)
	typedClient := ioc.InitESClient()
	articleSearchDAO := dao.NewElasticArticleDAO(typedClient)
	articleSearchRepository := repository.NewESArticleSearchRepository(articleSearchDAO)
	ollamaEmbeddingConfig := ioc.InitOllamaEmbeddingConfig()
	embeddingConfig := ioc.InitEmbeddingConfig()
	embeddingClient := ioc.InitEmbeddingClient(ollamaEmbeddingConfig, embeddingConfig, cmdable, loggerX)
	articleSearchService := service.NewArticleSearchService(articleSearchRepository, embeddingClient, loggerX)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleCache, loggerX)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	toolExecutor := service.NewAIChatToolExecutor(articleSearchService, articleReaderService, interactionRepository, loggerX)
	eventStreamer := streamer.NewRedisStreamer(cmdable)
	chatService := service.NewAIChatService(conversationRepository, messageRepository, llmClient, articleSearchService, toolExecutor, loggerX, eventStreamer)
	limiter := ioc.InitChatLimiter(cmdable)
	chatHandler := web.NewInternalChatHandler(chatService, loggerX, limiter)
	return chatHandler
}

// wire.go:

var infraSvcProvider = wire.NewSet(
	InitRedis,
	InitDB,
	InitLogger,
)

var userSvcProvider = wire.NewSet(dao.NewGormUserDAO, cache.NewRedisUserCache, repository.NewRedisUserRepository, service.NewInternalUserService)

var searchSvcProvider = wire.NewSet(ioc.InitESClient, ioc.InitOllamaEmbeddingConfig, ioc.InitEmbeddingConfig, ioc.InitEmbeddingClient, dao.NewElasticArticleDAO, repository.NewESArticleSearchRepository, service.NewArticleSearchService)

var articleSvcProvider = wire.NewSet(dao.NewGormArticleAuthorDAO, dao.NewGormArticleReaderDAO, cache.NewRedisArticleCache, repository.NewCacheArticleAuthorRepository, repository.NewCacheArticleReaderRepository, service.NewInternalArticleAuthorService, service.NewInternalArticleReaderService, interactionSvcProvider,
	searchSvcProvider,
)

var articleReaderSvcProvider = wire.NewSet(dao.NewGormArticleReaderDAO, cache.NewRedisArticleCache, repository.NewCacheArticleReaderRepository, service.NewInternalArticleReaderService, interactionSvcProvider)

var interactionSvcProvider = wire.NewSet(dao.NewGormInteractionDAO, cache.NewRedisInteractionCache, repository.NewCacheInteractionRepository, service.NewInternalInteractionService)

var clickEventSvcProvider = wire.NewSet(dao.NewGormAIClickEventDAO, cache.NewRedisAIClickEventCache, repository.NewCacheAIClickEventRepository, service.NewAIClickEventService)

var polishSvcProvider = wire.NewSet(service.NewAIArticlePolishService)

var chatSvcProvider = wire.NewSet(ioc.InitLLMConfig, ioc.InitLLMClient, ioc.InitChatLimiter, dao.NewGormConversationDAO, dao.NewGormMessageDAO, cache.NewRedisConversationCache, cache.NewRedisMessageCache, repository.NewCacheConversationRepository, repository.NewCacheMessageRepository, service.NewAIChatService, service.NewAIChatToolExecutor, streamer.NewRedisStreamer)
