// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"fmt"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	prometheus2 "github.com/prometheus/client_golang/prometheus"
	"github.com/redis/go-redis/v9"
	"github.com/robfig/cron/v3"
	"go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin"
	"go.opentelemetry.io/otel/trace"
	"go.opentelemetry.io/otel/trace/noop"

	"github.com/webook/internal/consts"
	"github.com/webook/internal/ioc"
	"github.com/webook/internal/job"
	"github.com/webook/internal/repository"
	"github.com/webook/internal/repository/cache"
	"github.com/webook/internal/repository/dao"
	"github.com/webook/internal/service"
	"github.com/webook/internal/web"
	prometheus3 "github.com/webook/pkg/cronx/prometheus"
	"github.com/webook/pkg/ginx/middleware/metrics"
	"github.com/webook/pkg/jwtx"
	"github.com/webook/pkg/logger"
	"github.com/webook/pkg/redislockx"
	"github.com/webook/pkg/redislockx/prometheus"
)

// Injectors from wire.go:

// 这个需要登录权限
func InitWebServer() *gin.Engine {
	loggerX := InitLogger()
	cmdable := InitRedis()
	tracerProvider := provideNoopTracerProvider()
	v := provideTestMiddlewares(loggerX, cmdable, tracerProvider)
	handler := ioc.InitJwtHandler(cmdable)
	db := InitDB()
	userDAO := dao.NewGormUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewRedisUserRepository(userDAO, userCache)
	userService := service.NewInternalUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewRedisCodeRepository(codeCache)
	smsService := ioc.InitSmsService(cmdable, loggerX)
	codeService := service.NewSmsCodeService(codeRepository, smsService)
	userHandler := web.NewInternalUserHandler(handler, userService, codeService, loggerX)
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable, loggerX)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderNewDAO := dao.NewGormArticleReaderNewDAO(db)
	switchReader := ioc.InitMigratorSDKSwitchReader(cmdable, loggerX)
	dualWriter := ioc.InitMigratorSDKDualWriter(cmdable, loggerX)
	taskName := ioc.InitMigratorSDKTaskName()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleReaderNewDAO, articleCache, switchReader, dualWriter, taskName, loggerX)
	typedClient := ioc.InitESClient()
	articleSearchDAO := dao.NewElasticArticleDAO(typedClient)
	articleSearchRepository := repository.NewESArticleSearchRepository(articleSearchDAO)
	ollamaConfig := ioc.InitOllamaEmbeddingConfig()
	config := ioc.InitEmbeddingConfig()
	client := ioc.InitEmbeddingClient(ollamaConfig, config, cmdable, loggerX)
	articleSearchService := service.NewArticleSearchService(articleSearchRepository, client, loggerX)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository, articleSearchService, loggerX)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, loggerX)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	oAuth2Service := ioc.InitWechatOAuth2Service()
	oAuth2Handler := web.NewOAuth2WechatHandler(handler, oAuth2Service, userService)
	articleSearchHandler := web.NewInternalArticleSearchHandler(articleSearchService, loggerX)
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	clickEventCache := cache.NewRedisAIClickEventCache(cmdable)
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	clickEventHandler := web.NewAIClickEventHandler(clickEventService, loggerX)
	llmConfig := ioc.InitLLMConfig()
	llmClient := ioc.InitLLMClient(llmConfig, loggerX)
	articlePolishService := service.NewAIArticlePolishService(llmClient)
	articlePolishHandler := web.NewAIArticlePolishHandler(articlePolishService, cmdable, loggerX)
	rankingCache := cache.NewRedisArticleRankingCache(cmdable, loggerX)
	rankingDAO := dao.NewGormArticleRankingDAO(db)
	rankingRepository := repository.NewCacheArticleRankingRepository(rankingCache, rankingDAO, loggerX)
	rankingService := service.NewArticleRankingService(rankingRepository, articleReaderRepository, interactionRepository, clickEventService, loggerX)
	rankingHandler := web.NewArticleRankingHandler(rankingService, loggerX)
	engine := ioc.InitWebServer(v, userHandler, articleAuthorHandler, articleReaderHandler, interactionHandler, oAuth2Handler, articleSearchHandler, clickEventHandler, articlePolishHandler, rankingHandler)
	return engine
}

func InitArticleAuthorHandler() web.ArticleAuthorHandler {
	db := InitDB()
	articleAuthorDAO := dao.NewGormArticleAuthorDAO(db)
	cmdable := InitRedis()
	loggerX := InitLogger()
	articleCache := cache.NewRedisArticleCache(cmdable, loggerX)
	articleAuthorRepository := repository.NewCacheArticleAuthorRepository(articleAuthorDAO, articleCache)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderNewDAO := dao.NewGormArticleReaderNewDAO(db)
	switchReader := ioc.InitMigratorSDKSwitchReader(cmdable, loggerX)
	dualWriter := ioc.InitMigratorSDKDualWriter(cmdable, loggerX)
	taskName := ioc.InitMigratorSDKTaskName()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleReaderNewDAO, articleCache, switchReader, dualWriter, taskName, loggerX)
	typedClient := ioc.InitESClient()
	articleSearchDAO := dao.NewElasticArticleDAO(typedClient)
	articleSearchRepository := repository.NewESArticleSearchRepository(articleSearchDAO)
	ollamaConfig := ioc.InitOllamaEmbeddingConfig()
	config := ioc.InitEmbeddingConfig()
	client := ioc.InitEmbeddingClient(ollamaConfig, config, cmdable, loggerX)
	articleSearchService := service.NewArticleSearchService(articleSearchRepository, client, loggerX)
	articleAuthorService := service.NewInternalArticleAuthorService(articleAuthorRepository, articleReaderRepository, articleSearchService, loggerX)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	articleAuthorHandler := web.NewInternalArticleAuthorHandler(articleAuthorService, interactionService, loggerX)
	return articleAuthorHandler
}

func InitArticleReaderHandler() web.ArticleReaderHandler {
	db := InitDB()
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderNewDAO := dao.NewGormArticleReaderNewDAO(db)
	cmdable := InitRedis()
	loggerX := InitLogger()
	articleCache := cache.NewRedisArticleCache(cmdable, loggerX)
	switchReader := ioc.InitMigratorSDKSwitchReader(cmdable, loggerX)
	dualWriter := ioc.InitMigratorSDKDualWriter(cmdable, loggerX)
	taskName := ioc.InitMigratorSDKTaskName()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleReaderNewDAO, articleCache, switchReader, dualWriter, taskName, loggerX)
	articleReaderService := service.NewInternalArticleReaderService(articleReaderRepository)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	articleReaderHandler := web.NewInternalArticleReaderHandler(articleReaderService, interactionService, loggerX)
	return articleReaderHandler
}

func InitInteractionHandler() web.InteractionHandler {
	db := InitDB()
	interactionDAO := dao.NewGormInteractionDAO(db)
	cmdable := InitRedis()
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	loggerX := InitLogger()
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	interactionService := service.NewInternalInteractionService(interactionRepository)
	interactionHandler := web.NewInternalInteractionHandler(interactionService, loggerX)
	return interactionHandler
}

func InitArticlePolishHandler() web.ArticlePolishHandler {
	config := ioc.InitLLMConfig()
	loggerX := InitLogger()
	client := ioc.InitLLMClient(config, loggerX)
	articlePolishService := service.NewAIArticlePolishService(client)
	cmdable := InitRedis()
	articlePolishHandler := web.NewAIArticlePolishHandler(articlePolishService, cmdable, loggerX)
	return articlePolishHandler
}

func InitClickEventHandler() web.ClickEventHandler {
	db := InitDB()
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	cmdable := InitRedis()
	clickEventCache := cache.NewRedisAIClickEventCache(cmdable)
	loggerX := InitLogger()
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	clickEventHandler := web.NewAIClickEventHandler(clickEventService, loggerX)
	return clickEventHandler
}

// InitRankingCron 集成测试用：拉起完整 cron + lock + wrapper + RankingJob 链路，
// 返回 cleanup 验证 graceful shutdown。每次独立 prometheus Registry。
func InitRankingCron() (*cron.Cron, func()) {
	cmdable := InitRedis()
	loggerX := InitLogger()
	rankingCache := cache.NewRedisArticleRankingCache(cmdable, loggerX)
	db := InitDB()
	rankingDAO := dao.NewGormArticleRankingDAO(db)
	rankingRepository := repository.NewCacheArticleRankingRepository(rankingCache, rankingDAO, loggerX)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	articleReaderNewDAO := dao.NewGormArticleReaderNewDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable, loggerX)
	switchReader := ioc.InitMigratorSDKSwitchReader(cmdable, loggerX)
	dualWriter := ioc.InitMigratorSDKDualWriter(cmdable, loggerX)
	taskName := ioc.InitMigratorSDKTaskName()
	articleReaderRepository := repository.NewCacheArticleReaderRepository(articleReaderDAO, articleReaderNewDAO, articleCache, switchReader, dualWriter, taskName, loggerX)
	interactionDAO := dao.NewGormInteractionDAO(db)
	interactionCache := cache.NewRedisInteractionCache(cmdable)
	interactionRepository := repository.NewCacheInteractionRepository(interactionDAO, interactionCache, loggerX)
	clickEventDAO := dao.NewGormAIClickEventDAO(db)
	clickEventCache := cache.NewRedisAIClickEventCache(cmdable)
	clickEventRepository := repository.NewCacheAIClickEventRepository(clickEventDAO, clickEventCache, loggerX)
	clickEventService := service.NewAIClickEventService(clickEventRepository)
	rankingService := service.NewArticleRankingService(rankingRepository, articleReaderRepository, interactionRepository, clickEventService, loggerX)
	client := provideTestLockClient(cmdable)
	metrics := provideTestCronMetrics()
	wrapper := ioc.InitCronWrapper(client, metrics, loggerX)
	rankingJob := job.NewRankingJob(rankingService, wrapper)
	cronCron, cleanup := ioc.InitCron(rankingJob, loggerX)
	return cronCron, func() {
		cleanup()
	}
}

// wire.go:

// 集成测试不连真实 OTel Collector，注入 Noop TracerProvider 满足依赖
func provideNoopTracerProvider() trace.TracerProvider {
	return noop.NewTracerProvider()
}

// 集成测试每次调用都给独立 prometheus Registry，避免 MustRegister 重复 panic。
// 生产 ioc.InitLockClient / InitCronMetrics 走 DefaultRegisterer，跨测试调用会撞名。
func provideTestLockClient(cmd redis.Cmdable) redislockx.Client {
	return prometheus.NewPrometheusBuilder("test", "lock", "test").
		Registry(prometheus2.NewRegistry()).
		Build(redislockx.NewClient(cmd))
}

func provideTestCronMetrics() *prometheus3.Metrics {
	return prometheus3.NewPrometheusBuilder("test", "cron", "test").
		Registry(prometheus2.NewRegistry()).Build()
}

// provideTestMiddlewares 与 ioc.InitMiddlewares 同结构，但 metrics 走独立 Registry，
// 避免每个集成测试 SetupSuite 调 InitWebServer 时 DefaultRegisterer.MustRegister 重复 panic。
// 省略 cors / 限流 / logger（httptest 无 cross-origin、不需限流、避免输出污染）。
func provideTestMiddlewares(l logger.LoggerX, cmd redis.Cmdable, tp trace.TracerProvider) []gin.HandlerFunc {
	return []gin.HandlerFunc{metrics.NewPrometheusBuilder("test", "http", "requests", "test").
		WithCounter().WithHistogram().WithSummary().WithInFlight().
		Registry(prometheus2.NewRegistry()).
		Build(), otelgin.Middleware("webook-test", otelgin.WithTracerProvider(tp)), cors.New(cors.Config{AllowOriginFunc: func(string) bool { return true }}), jwtx.NewMiddlewareBuilder(jwtx.MiddlewareConfig{
		AccessKey: consts.AccessKey,
		UserKey:   consts.UserKey,
		Session: func(ctx *gin.Context, ssid string) bool {
			cnt, err := cmd.Exists(ctx, fmt.Sprintf(consts.UserSsidPattern, ssid)).Result()
			return err == nil && cnt > 0
		},
	}).
		IgnoredPaths("/user/register", "/user/login", "/user/refresh_token",
			"/user/login_sms/code/send", "/user/login_sms",
			"/oauth2/wechat/authurl", "/oauth2/wechat/callback",
			"/article/reader/detail", "/article/reader/page",
			"/interaction/view", "/interaction/detail",
			"/article/ranking/page", "/article/ranking/archive/dates",
			"/metrics").
		Build(),
	}
}

var infraSvcProvider = wire.NewSet(
	InitRedis,
	InitDB,
	InitLogger,
)

var userSvcProvider = wire.NewSet(dao.NewGormUserDAO, cache.NewRedisUserCache, repository.NewRedisUserRepository, service.NewInternalUserService)

var searchSvcProvider = wire.NewSet(ioc.InitESClient, ioc.InitOllamaEmbeddingConfig, ioc.InitEmbeddingConfig, ioc.InitEmbeddingClient, dao.NewElasticArticleDAO, repository.NewESArticleSearchRepository, service.NewArticleSearchService)

var articleSvcProvider = wire.NewSet(dao.NewGormArticleAuthorDAO, dao.NewGormArticleReaderDAO, dao.NewGormArticleReaderNewDAO, cache.NewRedisArticleCache, repository.NewCacheArticleAuthorRepository, repository.NewCacheArticleReaderRepository, service.NewInternalArticleAuthorService, service.NewInternalArticleReaderService, ioc.InitMigratorSDKSwitchReader, ioc.InitMigratorSDKDualWriter, ioc.InitMigratorSDKTaskName, interactionSvcProvider,
	searchSvcProvider,
)

var articleReaderSvcProvider = wire.NewSet(dao.NewGormArticleReaderDAO, dao.NewGormArticleReaderNewDAO, cache.NewRedisArticleCache, repository.NewCacheArticleReaderRepository, service.NewInternalArticleReaderService, ioc.InitMigratorSDKSwitchReader, ioc.InitMigratorSDKDualWriter, ioc.InitMigratorSDKTaskName, interactionSvcProvider)

var interactionSvcProvider = wire.NewSet(dao.NewGormInteractionDAO, cache.NewRedisInteractionCache, repository.NewCacheInteractionRepository, service.NewInternalInteractionService)

var clickEventSvcProvider = wire.NewSet(dao.NewGormAIClickEventDAO, cache.NewRedisAIClickEventCache, repository.NewCacheAIClickEventRepository, service.NewAIClickEventService)

var polishSvcProvider = wire.NewSet(service.NewAIArticlePolishService)

// 文章榜单：集成测试不拉起 cron
var articleRankingSvcProvider = wire.NewSet(dao.NewGormArticleRankingDAO, cache.NewRedisArticleRankingCache, repository.NewCacheArticleRankingRepository, service.NewArticleRankingService, web.NewArticleRankingHandler)

// llmSvcProvider 仅 LLM 相关 provider，供 article_polish 用。
// 原 chatSvcProvider 已随 chat 服务搬到 chat/wire.go。
var llmSvcProvider = wire.NewSet(ioc.InitLLMConfig, ioc.InitLLMClient)
