// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/web/jwt/types.go
//
// Generated by this command:
//
//	mockgen -source=./internal/web/jwt/types.go -package=jwtmocks -destination=./internal/web/jwt/mocks/jwt_mock.go
//

// Package jwtmocks is a generated GoMock package.
package jwtmocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockJwtHandler is a mock of JwtHandler interface.
type MockJwtHandler struct {
	ctrl     *gomock.Controller
	recorder *MockJwtHandlerMockRecorder
	isgomock struct{}
}

// MockJwtHandlerMockRecorder is the mock recorder for MockJwtHandler.
type MockJwtHandlerMockRecorder struct {
	mock *MockJwtHandler
}

// NewMockJwtHandler creates a new mock instance.
func NewMockJwtHandler(ctrl *gomock.Controller) *MockJwtHandler {
	mock := &MockJwtHandler{ctrl: ctrl}
	mock.recorder = &MockJwtHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtHandler) EXPECT() *MockJwtHandlerMockRecorder {
	return m.recorder
}

// CheckSession mocks base method.
func (m *MockJwtHandler) CheckSession(ctx *gin.Context, ssid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSession", ctx, ssid)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckSession indicates an expected call of CheckSession.
func (mr *MockJwtHandlerMockRecorder) CheckSession(ctx, ssid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSession", reflect.TypeOf((*MockJwtHandler)(nil).CheckSession), ctx, ssid)
}

// ClearToken mocks base method.
func (m *MockJwtHandler) ClearToken(ctx *gin.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearToken", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearToken indicates an expected call of ClearToken.
func (mr *MockJwtHandlerMockRecorder) ClearToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearToken", reflect.TypeOf((*MockJwtHandler)(nil).ClearToken), ctx)
}

// ExtractToken mocks base method.
func (m *MockJwtHandler) ExtractToken(ctx *gin.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractToken", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExtractToken indicates an expected call of ExtractToken.
func (mr *MockJwtHandlerMockRecorder) ExtractToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractToken", reflect.TypeOf((*MockJwtHandler)(nil).ExtractToken), ctx)
}

// SetAccessToken mocks base method.
func (m *MockJwtHandler) SetAccessToken(ctx *gin.Context, userid int64, ssid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAccessToken", ctx, userid, ssid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAccessToken indicates an expected call of SetAccessToken.
func (mr *MockJwtHandlerMockRecorder) SetAccessToken(ctx, userid, ssid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccessToken", reflect.TypeOf((*MockJwtHandler)(nil).SetAccessToken), ctx, userid, ssid)
}

// SetLoginToken mocks base method.
func (m *MockJwtHandler) SetLoginToken(ctx *gin.Context, userid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLoginToken", ctx, userid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLoginToken indicates an expected call of SetLoginToken.
func (mr *MockJwtHandlerMockRecorder) SetLoginToken(ctx, userid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoginToken", reflect.TypeOf((*MockJwtHandler)(nil).SetLoginToken), ctx, userid)
}

// SetRefreshToken mocks base method.
func (m *MockJwtHandler) SetRefreshToken(ctx *gin.Context, userid int64, ssid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefreshToken", ctx, userid, ssid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRefreshToken indicates an expected call of SetRefreshToken.
func (mr *MockJwtHandlerMockRecorder) SetRefreshToken(ctx, userid, ssid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefreshToken", reflect.TypeOf((*MockJwtHandler)(nil).SetRefreshToken), ctx, userid, ssid)
}
