// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/feed.go
//
// Generated by this command:
//
//	mockgen -source=./service/feed.go -package=svcmocks -destination=./service/mocks/feed.mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/feed/domain"
)

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
	isgomock struct{}
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// Fanout mocks base method.
func (m *MockFeedService) Fanout(ctx context.Context, art domain.FeedArticle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fanout", ctx, art)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fanout indicates an expected call of Fanout.
func (mr *MockFeedServiceMockRecorder) Fanout(ctx, art any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fanout", reflect.TypeOf((*MockFeedService)(nil).Fanout), ctx, art)
}

// InvalidateInboxes mocks base method.
func (m *MockFeedService) InvalidateInboxes(ctx context.Context, uids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateInboxes", ctx, uids)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateInboxes indicates an expected call of InvalidateInboxes.
func (mr *MockFeedServiceMockRecorder) InvalidateInboxes(ctx, uids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateInboxes", reflect.TypeOf((*MockFeedService)(nil).InvalidateInboxes), ctx, uids)
}

// ListFeed mocks base method.
func (m *MockFeedService) ListFeed(ctx context.Context, uid, cursor int64, limit int) ([]domain.FeedItem, int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeed", ctx, uid, cursor, limit)
	ret0, _ := ret[0].([]domain.FeedItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListFeed indicates an expected call of ListFeed.
func (mr *MockFeedServiceMockRecorder) ListFeed(ctx, uid, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeed", reflect.TypeOf((*MockFeedService)(nil).ListFeed), ctx, uid, cursor, limit)
}

// NewCount mocks base method.
func (m *MockFeedService) NewCount(ctx context.Context, uid, since int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCount", ctx, uid, since)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCount indicates an expected call of NewCount.
func (mr *MockFeedServiceMockRecorder) NewCount(ctx, uid, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCount", reflect.TypeOf((*MockFeedService)(nil).NewCount), ctx, uid, since)
}

// Remove mocks base method.
func (m *MockFeedService) Remove(ctx context.Context, articleId, authorId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, articleId, authorId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFeedServiceMockRecorder) Remove(ctx, articleId, authorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFeedService)(nil).Remove), ctx, articleId, authorId)
}
