// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/boyxs/train-go/webook/pkg/grpcx"
	"github.com/boyxs/train-go/webook/search/grpc"
	"github.com/boyxs/train-go/webook/search/ioc"
	"github.com/boyxs/train-go/webook/search/repository"
	"github.com/boyxs/train-go/webook/search/service"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	loggerX := ioc.InitLogger()
	typedClient := ioc.InitESClient(loggerX)
	articleDAO := ioc.InitArticleDAO(typedClient, loggerX)
	articleRepository := repository.NewESArticleRepository(articleDAO)
	ollamaConfig := ioc.InitOllamaEmbeddingConfig()
	config := ioc.InitEmbeddingConfig()
	cmdable := ioc.InitRedis()
	embeddingClient := ioc.InitEmbeddingClient(ollamaConfig, config, cmdable, loggerX)
	articleService := service.NewInternalArticleService(articleRepository, embeddingClient, loggerX)
	searchServer := grpc.NewSearchServer(articleService)
	client, cleanup, err := ioc.InitEtcdClient()
	if err != nil {
		return App{}, nil, err
	}
	tracerProvider, cleanup2, err := ioc.InitOTel()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	server := ioc.InitGRPCServer(searchServer, client, loggerX, tracerProvider)
	app := App{
		GRPCServer: server,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App search 服务进程入口（纯 gRPC server）。
type App struct {
	GRPCServer *grpcx.Server
}
