// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"net/http"

	"github.com/robfig/cron/v3"

	"github.com/boyxs/train-go/webook/worker/consumer"
	"github.com/boyxs/train-go/webook/worker/ioc"
	"github.com/boyxs/train-go/webook/worker/job"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	timezoneReady := ioc.InitTimezone()
	client, cleanup, err := ioc.InitEtcdClient()
	if err != nil {
		return App{}, nil, err
	}
	prometheusBuilder := ioc.InitGRPCMetrics()
	tracerProvider, cleanup2, err := ioc.InitOTel()
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	coreConn, cleanup3, err := ioc.InitCoreConn(client, prometheusBuilder, tracerProvider)
	if err != nil {
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	rankingJobServiceClient := ioc.InitRankingJobClient(coreConn)
	universalClient := ioc.InitRedis()
	redislockClient := ioc.InitLockClient(universalClient)
	metrics := ioc.InitCronMetrics()
	loggerX := ioc.InitLogger()
	wrapper := ioc.InitCronWrapper(redislockClient, metrics, loggerX)
	rankingJob := job.NewRankingJob(rankingJobServiceClient, wrapper)
	cron, err := ioc.InitCron(timezoneReady, rankingJob)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	kafkaConfig := ioc.InitKafkaConfig()
	config := ioc.InitSaramaConfig(kafkaConfig)
	interactionConn, cleanup4, err := ioc.InitInteractionConn(client, prometheusBuilder, tracerProvider)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	interactionServiceClient := ioc.InitInteractionClient(interactionConn)
	consumerConfig := ioc.InitConsumerConfig(kafkaConfig)
	interactionConsumer := consumer.NewInteractionConsumer(config, interactionServiceClient, consumerConfig, loggerX)
	serveMux := ioc.InitWebServer()
	app := App{
		Cron:     cron,
		Consumer: interactionConsumer,
		Web:      serveMux,
	}
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App worker 调度器进程入口：cron 定时任务 + Kafka 消费者 + 最小 HTTP(metrics/health)。
type App struct {
	Cron     *cron.Cron
	Consumer *consumer.InteractionConsumer
	Web      *http.ServeMux
}
