// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/boyxs/train-go/webook/internal/ioc"
	"github.com/boyxs/train-go/webook/internal/repository/dao"
)

// Injectors from wire.go:

// InitSearchBackfiller 复用 core 的 infra + 下游 gRPC client provider 装配回填工具。
// 仅取回填所需子集：DB（源库）+ etcd 发现 + search/tag client，不拉起 web/gRPC server。
func InitSearchBackfiller() (*SearchBackfiller, func(), error) {
	timezoneReady := ioc.InitTimezone()
	loggerX := ioc.InitLogger()
	db := ioc.InitDB(timezoneReady, loggerX)
	articleReaderDAO := dao.NewGormArticleReaderDAO(db)
	client, cleanup, err := ioc.InitEtcdClient()
	if err != nil {
		return nil, nil, err
	}
	prometheusBuilder := ioc.InitGRPCMetrics()
	searchConn, cleanup2, err := ioc.InitSearchConn(client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	searchServiceClient := ioc.InitSearchClient(searchConn)
	tagConn, cleanup3, err := ioc.InitTagConn(client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tagServiceClient := ioc.InitTagClient(tagConn)
	searchBackfiller := NewSearchBackfiller(articleReaderDAO, searchServiceClient, tagServiceClient, loggerX)
	return searchBackfiller, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
