apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  # ReadWriteOnce 一个POD读写；
  # ReadOnlyMany  多个读，一个写；
  # ReadWriteMany 多个读写；
  accessModes:
    - ReadWriteOnce
#    - ReadOnlyMany
#    - ReadWriteMany
  hostPath:
    path: "/mnt/mysql"