// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/feed.go
//
// Generated by this command:
//
//	mockgen -source=./repository/feed.go -package=repomocks -destination=./repository/mocks/feed.mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/boyxs/train-go/webook/feed/domain"
)

// MockFeedRepository is a mock of FeedRepository interface.
type MockFeedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedRepositoryMockRecorder is the mock recorder for MockFeedRepository.
type MockFeedRepositoryMockRecorder struct {
	mock *MockFeedRepository
}

// NewMockFeedRepository creates a new mock instance.
func NewMockFeedRepository(ctrl *gomock.Controller) *MockFeedRepository {
	mock := &MockFeedRepository{ctrl: ctrl}
	mock.recorder = &MockFeedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedRepository) EXPECT() *MockFeedRepositoryMockRecorder {
	return m.recorder
}

// AppendInbox mocks base method.
func (m *MockFeedRepository) AppendInbox(ctx context.Context, uids []int64, item domain.FeedItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendInbox", ctx, uids, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendInbox indicates an expected call of AppendInbox.
func (mr *MockFeedRepositoryMockRecorder) AppendInbox(ctx, uids, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInbox", reflect.TypeOf((*MockFeedRepository)(nil).AppendInbox), ctx, uids, item)
}

// AppendOutboxIfExists mocks base method.
func (m *MockFeedRepository) AppendOutboxIfExists(ctx context.Context, authorId int64, item domain.FeedItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendOutboxIfExists", ctx, authorId, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendOutboxIfExists indicates an expected call of AppendOutboxIfExists.
func (mr *MockFeedRepositoryMockRecorder) AppendOutboxIfExists(ctx, authorId, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendOutboxIfExists", reflect.TypeOf((*MockFeedRepository)(nil).AppendOutboxIfExists), ctx, authorId, item)
}

// DelOutbox mocks base method.
func (m *MockFeedRepository) DelOutbox(ctx context.Context, authorId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelOutbox", ctx, authorId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelOutbox indicates an expected call of DelOutbox.
func (mr *MockFeedRepositoryMockRecorder) DelOutbox(ctx, authorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelOutbox", reflect.TypeOf((*MockFeedRepository)(nil).DelOutbox), ctx, authorId)
}

// FillOutbox mocks base method.
func (m *MockFeedRepository) FillOutbox(ctx context.Context, authorId int64, items []domain.FeedItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillOutbox", ctx, authorId, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// FillOutbox indicates an expected call of FillOutbox.
func (mr *MockFeedRepositoryMockRecorder) FillOutbox(ctx, authorId, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillOutbox", reflect.TypeOf((*MockFeedRepository)(nil).FillOutbox), ctx, authorId, items)
}

// InboxBuilt mocks base method.
func (m *MockFeedRepository) InboxBuilt(ctx context.Context, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InboxBuilt", ctx, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InboxBuilt indicates an expected call of InboxBuilt.
func (mr *MockFeedRepositoryMockRecorder) InboxBuilt(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InboxBuilt", reflect.TypeOf((*MockFeedRepository)(nil).InboxBuilt), ctx, uid)
}

// InboxSince mocks base method.
func (m *MockFeedRepository) InboxSince(ctx context.Context, uid, since int64, limit int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InboxSince", ctx, uid, since, limit)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InboxSince indicates an expected call of InboxSince.
func (mr *MockFeedRepositoryMockRecorder) InboxSince(ctx, uid, since, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InboxSince", reflect.TypeOf((*MockFeedRepository)(nil).InboxSince), ctx, uid, since, limit)
}

// Invalidate mocks base method.
func (m *MockFeedRepository) Invalidate(ctx context.Context, uids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, uids)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockFeedRepositoryMockRecorder) Invalidate(ctx, uids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockFeedRepository)(nil).Invalidate), ctx, uids)
}

// ReadBigv mocks base method.
func (m *MockFeedRepository) ReadBigv(ctx context.Context, uid int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBigv", ctx, uid)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBigv indicates an expected call of ReadBigv.
func (mr *MockFeedRepositoryMockRecorder) ReadBigv(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBigv", reflect.TypeOf((*MockFeedRepository)(nil).ReadBigv), ctx, uid)
}

// ReadInbox mocks base method.
func (m *MockFeedRepository) ReadInbox(ctx context.Context, uid, cursor int64, limit int) ([]domain.FeedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadInbox", ctx, uid, cursor, limit)
	ret0, _ := ret[0].([]domain.FeedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadInbox indicates an expected call of ReadInbox.
func (mr *MockFeedRepositoryMockRecorder) ReadInbox(ctx, uid, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadInbox", reflect.TypeOf((*MockFeedRepository)(nil).ReadInbox), ctx, uid, cursor, limit)
}

// ReadOutbox mocks base method.
func (m *MockFeedRepository) ReadOutbox(ctx context.Context, authorId, cursor int64, limit int) ([]domain.FeedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOutbox", ctx, authorId, cursor, limit)
	ret0, _ := ret[0].([]domain.FeedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOutbox indicates an expected call of ReadOutbox.
func (mr *MockFeedRepositoryMockRecorder) ReadOutbox(ctx, authorId, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOutbox", reflect.TypeOf((*MockFeedRepository)(nil).ReadOutbox), ctx, authorId, cursor, limit)
}

// SaveInbox mocks base method.
func (m *MockFeedRepository) SaveInbox(ctx context.Context, uid int64, items []domain.FeedItem, bigvs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveInbox", ctx, uid, items, bigvs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveInbox indicates an expected call of SaveInbox.
func (mr *MockFeedRepositoryMockRecorder) SaveInbox(ctx, uid, items, bigvs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveInbox", reflect.TypeOf((*MockFeedRepository)(nil).SaveInbox), ctx, uid, items, bigvs)
}
