// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"

	"github.com/webook/migrator/ioc"
	"github.com/webook/migrator/repository"
	"github.com/webook/migrator/repository/cache"
	"github.com/webook/migrator/repository/dao"
	"github.com/webook/migrator/service"
	"github.com/webook/migrator/service/replay"
	"github.com/webook/migrator/service/switching"
	"github.com/webook/migrator/web"
	"github.com/webook/migrator/web/middleware"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	loggerX := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	tracerProvider, cleanup, err := ioc.InitOTel()
	if err != nil {
		return App{}, nil, err
	}
	timezoneReady := ioc.InitTimezone()
	db := ioc.InitDB(timezoneReady, loggerX)
	auditLogDAO := dao.NewGormAuditLogDAO(db)
	auditLogRepository := repository.NewAuditLogRepository(auditLogDAO)
	auditMiddleware := middleware.NewAuditMiddleware(auditLogRepository, loggerX)
	v := ioc.InitMiddlewares(loggerX, cmdable, tracerProvider, auditMiddleware)
	taskDAO := dao.NewGormTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO, loggerX)
	throttleCache := cache.NewRedisThrottleCache(cmdable)
	throttleRepository := repository.NewThrottleRepository(throttleCache)
	taskService := service.NewTaskService(taskRepository, throttleRepository, loggerX)
	checkpointDAO := dao.NewGormCheckpointDAO(db)
	checkpointRepository := repository.NewCheckpointRepository(checkpointDAO)
	resolver := ioc.InitDBResolver(db)
	client := ioc.InitMongoClient(loggerX)
	sourceFactory := ioc.InitSourceFactory(db, loggerX, resolver, client)
	sinkFactory := ioc.InitSinkFactory(db, loggerX, resolver, client)
	fullEngine := ioc.InitFullEngine(taskService, checkpointRepository, sourceFactory, sinkFactory, loggerX)
	incrEngine := ioc.InitIncrEngine(taskService, checkpointRepository, sourceFactory, sinkFactory, loggerX)
	validateLogDAO := dao.NewGormValidateLogDAO(db)
	validateLogRepository := repository.NewValidateLogRepository(validateLogDAO)
	verifyEngine := ioc.InitVerifyEngine(taskService, validateLogRepository, sourceFactory, sinkFactory, loggerX)
	switchStateCache := cache.NewRedisSwitchStateCache(cmdable)
	switchStateRepository := repository.NewSwitchStateRepository(switchStateCache)
	switchService := switching.NewSwitchService(taskRepository, switchStateRepository, loggerX)
	deadLetterDAO := dao.NewGormDeadLetterDAO(db)
	deadLetterRepository := repository.NewDeadLetterRepository(deadLetterDAO)
	replayService := replay.NewReplayService(taskService, deadLetterRepository, sinkFactory, loggerX)
	taskHandler := web.NewTaskHandler(taskService, fullEngine, incrEngine, verifyEngine, switchService, replayService, sourceFactory, resolver, loggerX)
	migrationMetricsCollector := ioc.InitMigrationMetrics(incrEngine, deadLetterRepository, loggerX)
	engine := ioc.InitWebServer(v, taskHandler, migrationMetricsCollector)
	app := App{
		Server: engine,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// App migrator 服务进程入口。
type App struct {
	Server *gin.Engine
}
