// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/boyxs/train-go/webook/feed/grpc"
	"github.com/boyxs/train-go/webook/feed/ioc"
	"github.com/boyxs/train-go/webook/feed/repository"
	"github.com/boyxs/train-go/webook/feed/repository/cache"
	"github.com/boyxs/train-go/webook/feed/service"
	"github.com/boyxs/train-go/webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitApp() (App, func(), error) {
	cmdable := ioc.InitRedis()
	config := ioc.InitCacheConfig()
	feedCache := cache.NewRedisFeedCache(cmdable, config)
	feedRepository := repository.NewCacheFeedRepository(feedCache)
	client, cleanup, err := ioc.InitEtcdClient()
	if err != nil {
		return App{}, nil, err
	}
	prometheusBuilder := ioc.InitGRPCMetrics()
	loggerX := ioc.InitLogger()
	relationConn, cleanup2, err := ioc.InitRelationConn(client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	relationServiceClient := ioc.InitRelationClient(relationConn)
	coreConn, cleanup3, err := ioc.InitCoreConn(client, prometheusBuilder, loggerX)
	if err != nil {
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	articleReaderServiceClient := ioc.InitArticleClient(coreConn)
	serviceConfig := ioc.InitServiceConfig()
	feedService := service.NewInternalFeedService(feedRepository, relationServiceClient, articleReaderServiceClient, serviceConfig, loggerX)
	feedServer := grpc.NewFeedServer(feedService)
	tracerProvider, cleanup4, err := ioc.InitOTel()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return App{}, nil, err
	}
	server := ioc.InitGRPCServer(feedServer, client, prometheusBuilder, loggerX, tracerProvider)
	app := App{
		GRPCServer: server,
	}
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App feed 服务进程入口（纯同步 gRPC server；无 MySQL，数据全 Redis 投影）。
type App struct {
	GRPCServer *grpcx.Server
}
