// Code generated by MockGen. DO NOT EDIT.
// Source: ./events/article/producer.go
//
// Generated by this command:
//
//	mockgen -source=./events/article/producer.go -package=articleevtmocks -destination=./events/article/mocks/producer_mock.go
//

// Package articleevtmocks is a generated GoMock package.
package articleevtmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	article "github.com/boyxs/train-go/webook/internal/events/article"
)

// MockArticleEventProducer is a mock of ArticleEventProducer interface.
type MockArticleEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockArticleEventProducerMockRecorder
	isgomock struct{}
}

// MockArticleEventProducerMockRecorder is the mock recorder for MockArticleEventProducer.
type MockArticleEventProducerMockRecorder struct {
	mock *MockArticleEventProducer
}

// NewMockArticleEventProducer creates a new mock instance.
func NewMockArticleEventProducer(ctrl *gomock.Controller) *MockArticleEventProducer {
	mock := &MockArticleEventProducer{ctrl: ctrl}
	mock.recorder = &MockArticleEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleEventProducer) EXPECT() *MockArticleEventProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockArticleEventProducer) Produce(ctx context.Context, evt article.ArticleEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockArticleEventProducerMockRecorder) Produce(ctx, evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockArticleEventProducer)(nil).Produce), ctx, evt)
}
