// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire/repository"
	"wire/repository/dao"
)

// Injectors from wire.go:

func InitUserRepository() *repository.UserRepository {
	cmdable := InitRedis()
	userDAO := dao.NewUserDAO(cmdable)
	userRepository := repository.NewUserRepository(userDAO)
	return userRepository
}
