// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/ai/embedding.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/ai/embedding.go -package=aimocks -destination=./internal/service/ai/mocks/embedding_mock.go
//

// Package aimocks is a generated GoMock package.
package aimocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmbeddingClient is a mock of EmbeddingClient interface.
type MockEmbeddingClient struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingClientMockRecorder
	isgomock struct{}
}

// MockEmbeddingClientMockRecorder is the mock recorder for MockEmbeddingClient.
type MockEmbeddingClientMockRecorder struct {
	mock *MockEmbeddingClient
}

// NewMockEmbeddingClient creates a new mock instance.
func NewMockEmbeddingClient(ctrl *gomock.Controller) *MockEmbeddingClient {
	mock := &MockEmbeddingClient{ctrl: ctrl}
	mock.recorder = &MockEmbeddingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingClient) EXPECT() *MockEmbeddingClientMockRecorder {
	return m.recorder
}

// Embed mocks base method.
func (m *MockEmbeddingClient) Embed(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockEmbeddingClientMockRecorder) Embed(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockEmbeddingClient)(nil).Embed), ctx, text)
}
