// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/ai/llm.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/ai/llm.go -package=aimocks -destination=./internal/service/ai/mocks/llm_mock.go
//

// Package aimocks is a generated GoMock package.
package aimocks

import (
	context "context"
	reflect "reflect"

	ai "github.com/webook/internal/service/ai"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
	isgomock struct{}
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockLLMClient) Chat(ctx context.Context, messages []ai.ChatMessage) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, messages)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockLLMClientMockRecorder) Chat(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockLLMClient)(nil).Chat), ctx, messages)
}

// ChatStream mocks base method.
func (m *MockLLMClient) ChatStream(ctx context.Context, messages []ai.ChatMessage, tools []ai.Tool) (<-chan ai.StreamChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, messages, tools)
	ret0, _ := ret[0].(<-chan ai.StreamChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockLLMClientMockRecorder) ChatStream(ctx, messages, tools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockLLMClient)(nil).ChatStream), ctx, messages, tools)
}
